#!/usr/bin/env python3
# Converts mason's 4 directional sprites (source: xenodorian/CryMon,
# public/sprites/mason/{down,up,left,right}-1.png) into a C header of
# raw RGB565 pixel arrays for the bare-metal Dreamcast port's
# put_pixel-based framebuffer. Downscaled 2x (48x64 -> 24x32, nearest
# neighbor / pixel-doubled source, so this is decimation, not a blur)
# to fit the port's 20px room tiles. Pixels are encoded as the key
# color 0xF81F (magenta) and skipped by the blitter at draw time when
# alpha < 128; the source art actually has anti-aliased edges (checked:
# alpha values span the full 0-255 range, not just 0/255), so this
# cutoff is an approximation -- edge pixels end up fully opaque or
# fully see-through, not blended. Good enough to verify sprites load
# and draw; true alpha blending isn't attempted here.
#
# Usage: gen_sprites.py <path-to-xenodorian/CryMon-checkout>
# Requires Pillow (pip install pillow).

import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'src', 'sprites_mason.h')
DIRS = ['down', 'up', 'left', 'right']
SRC_W, SRC_H = 48, 64
DST_W, DST_H = 24, 32
KEY = 0xF81F  # magenta, matches nothing in mason's palette (checked below)

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def convert(path):
    im = Image.open(path).convert('RGBA')
    assert im.size == (SRC_W, SRC_H), (path, im.size)
    px = im.load()
    out = []
    for dy in range(DST_H):
        for dx in range(DST_W):
            sx, sy = dx * 2, dy * 2
            r, g, b, a = px[sx, sy]
            if a < 128:
                out.append(KEY)
            else:
                v = rgb565(r, g, b)
                if v == KEY:
                    v ^= 0x0001  # nudge off the key color, imperceptible
                out.append(v)
    return out

def main():
    if len(sys.argv) != 2:
        sys.exit('usage: gen_sprites.py <path-to-xenodorian/CryMon-checkout>')
    src = os.path.join(sys.argv[1], 'public', 'sprites', 'mason')

    lines = []
    lines.append('/* Generated by tools/gen_sprites.py from xenodorian/CryMon')
    lines.append(' * public/sprites/mason/{dir}-1.png. Do not hand-edit --')
    lines.append(' * regenerate from source art instead. */')
    lines.append('')
    lines.append('#define MASON_SPRITE_W %d' % DST_W)
    lines.append('#define MASON_SPRITE_H %d' % DST_H)
    lines.append('#define MASON_SPRITE_KEY 0x%04X' % KEY)
    lines.append('')
    for d in DIRS:
        pixels = convert(os.path.join(src, '%s-1.png' % d))
        lines.append('static const unsigned short mason_%s[MASON_SPRITE_W * MASON_SPRITE_H] = {' % d)
        for row in range(DST_H):
            vals = pixels[row * DST_W:(row + 1) * DST_W]
            lines.append('    ' + ', '.join('0x%04X' % v for v in vals) + ',')
        lines.append('};')
        lines.append('')
    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote', OUT)

if __name__ == '__main__':
    main()
