#!/usr/bin/env python3
# Converts the room's sprite art -- the player (max, four directional
# frames) and the four furniture props (bed-father, bed-empty, shelf,
# crate) -- from xenodorian/CryMon's public/sprites/{max,props}/*.png
# into a C header of raw RGB565 pixel arrays for the bare-metal
# Dreamcast port's put_pixel-based framebuffer.
#
# Each sprite is downscaled with nearest-neighbor resampling to a
# fixed target size (chosen to roughly match the room's 20px tiles;
# see TARGETS below) and color-keyed for transparency: any source
# pixel with alpha < 128 becomes the key color (0xF81F, magenta, one
# per sprite -- picked to not collide with that sprite's own opaque
# colors, checked below) and is skipped by the blitter at draw time.
# The source art has anti-aliased edges (alpha spans the full 0-255
# range, not just 0/255), so this hard cutoff is an approximation --
# edge pixels end up fully opaque or fully see-through, not blended.
# Good enough to verify sprites load and draw; true alpha blending
# isn't attempted here.
#
# Usage: gen_sprites.py <path-to-xenodorian/CryMon-checkout>
# Requires Pillow (pip install pillow).

import os
import sys

from PIL import Image

HERE = os.path.dirname(os.path.abspath(__file__))
OUT = os.path.join(HERE, '..', 'src', 'sprites.h')
KEY = 0xF81F  # magenta

# name -> (source relative to CryMon repo root, target W, target H)
PLAYER_DIRS = ['down', 'up', 'left', 'right']
PLAYER_SRC_W, PLAYER_SRC_H = 48, 64
PLAYER_DST_W, PLAYER_DST_H = 24, 32

# Target sizes picked to roughly match the room's 20px tiles while
# keeping each prop's real aspect ratio (the sizes previously
# hardcoded as flat-rect placeholders in main.c did not match the
# actual art's proportions).
PROPS = {
    'bed_father': ('props/bed-father.png', 42, 40),
    'bed_empty':  ('props/bed-empty.png', 42, 40),
    'shelf':      ('props/shelf.png', 34, 31),
    'crate':      ('props/crate.png', 24, 25),
}

def rgb565(r, g, b):
    return ((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3)

def encode(im, dst_w, dst_h):
    im = im.convert('RGBA').resize((dst_w, dst_h), Image.NEAREST)
    px = im.load()
    out = []
    for y in range(dst_h):
        for x in range(dst_w):
            r, g, b, a = px[x, y]
            if a < 128:
                out.append(KEY)
            else:
                v = rgb565(r, g, b)
                if v == KEY:
                    v ^= 0x0001  # nudge off the key color, imperceptible
                out.append(v)
    return out

def emit_array(lines, name, pixels, w, h):
    lines.append('static const unsigned short %s[%d * %d] = {' % (name, w, h))
    for row in range(h):
        vals = pixels[row * w:(row + 1) * w]
        lines.append('    ' + ', '.join('0x%04X' % v for v in vals) + ',')
    lines.append('};')
    lines.append('')

def main():
    if len(sys.argv) != 2:
        sys.exit('usage: gen_sprites.py <path-to-xenodorian/CryMon-checkout>')
    root = os.path.join(sys.argv[1], 'public', 'sprites')

    lines = []
    lines.append('/* Generated by tools/gen_sprites.py from xenodorian/CryMon')
    lines.append(' * public/sprites/max/ and public/sprites/props/ PNGs.')
    lines.append(' * Do not hand-edit -- regenerate from source art instead. */')
    lines.append('')
    lines.append('#define SPRITE_KEY 0x%04X' % KEY)
    lines.append('')

    lines.append('#define MAX_SPRITE_W %d' % PLAYER_DST_W)
    lines.append('#define MAX_SPRITE_H %d' % PLAYER_DST_H)
    lines.append('')
    for d in PLAYER_DIRS:
        im = Image.open(os.path.join(root, 'max', '%s-1.png' % d))
        assert im.size == (PLAYER_SRC_W, PLAYER_SRC_H), (d, im.size)
        pixels = encode(im, PLAYER_DST_W, PLAYER_DST_H)
        emit_array(lines, 'max_%s' % d, pixels, PLAYER_DST_W, PLAYER_DST_H)

    for name, (relpath, w, h) in PROPS.items():
        im = Image.open(os.path.join(root, relpath))
        pixels = encode(im, w, h)
        lines.append('#define PROP_%s_W %d' % (name.upper(), w))
        lines.append('#define PROP_%s_H %d' % (name.upper(), h))
        emit_array(lines, 'prop_%s' % name, pixels, w, h)

    with open(OUT, 'w') as f:
        f.write('\n'.join(lines) + '\n')
    print('wrote', OUT)

if __name__ == '__main__':
    main()
