/*
 * CryMon - Dreamcast port, step 5: full world navigation. All 4 of
 * the reference's maps (HOUSE, VELD, FOREST, GROVE) now exist, with
 * camera scrolling for the three that are bigger than the screen, and
 * every door/warp tile between them works, matching state.lua's warp
 * chain (house<->veld<->forest<->grove) including the house door's
 * gate on gotShelf. Still not ported: any NPC, soldier, wild
 * encounter, the battle system, catching, the shop, or endings --
 * VELD/FOREST/GROVE are walkable but otherwise empty; their many
 * NPC/decoration tile marks (Q, K, M, V, X, J, T, 1-9, etc.) render
 * with paintTile's colors but have no actors or interactions behind
 * them yet. See the per-system notes further down for exactly what
 * each ported piece does and doesn't cover.
 *
 * Bare-metal, no KallistiOS/BIOS calls. Video setup, vblank sync, and
 * the Maple controller driver are unchanged from step 1 (see that
 * commit / hello-world-dreamcast/src/hello.c for the full derivation
 * notes against KallistiOS's real source).
 *
 * Room layout, tile colors, solid/walkable tiles, prop positions and
 * sizes, player movement speed, and the interactable dialogue/state
 * are all taken from the reference implementation (xenodorian/CryMon):
 *   - love/game/src/data.lua: data.HOUSE (tile grid), data.isSolidTile
 *     (SOLID_SET), data.spawnOf (tile-center world coords), data.TALK
 *     (dialogue text, ported verbatim below except upper-cased and
 *     stripped of punctuation our font can't render), data.START_BAG
 *     / data.START_MARKS (starting bag/marks -- see the Bag struct
 *     below), data.mintMonster (Quillpup's fixed lv3/34hp, see
 *     QUILLPUP_LV/QUILLPUP_MAX_HP below).
 *   - love/game/src/draw.lua: paintTile (tile colors). draw.actor's
 *     colored-silhouette fallback is no longer used for the player --
 *     see sprites.h below.
 *   - love/game/src/render.lua: drawWorld (prop positions used only
 *     to place each prop at its mark's tile center; the sizes
 *     themselves now come from the real art, see sprites.h), the
 *     movement code (speed = 110px/sec at the original's 32px tile
 *     size), and drawBag()/drawParty() (see draw_bag_menu/
 *     draw_party_menu below -- ported as read-only text-row lists,
 *     no item icons, no item-use, no lead-switching, since nothing in
 *     this room's scope needs them yet).
 *   - love/game/src/state.lua: interact()'s MAP_HOUSE branch (the
 *     bed/father/shelf/crate logic and state flags below match it
 *     line for line), sayn() (one dialogue beat shown per A-press,
 *     movement frozen while a sequence is active -- state.lua's
 *     MODE.TALK), and the BAG/PARTY mode update (open/close only, no
 *     cursor logic -- matches the reference, which also only handles
 *     open/close for these two modes).
 * No battle system is ported -- Quillpup is tracked as a bare
 * got_shelf flag plus fixed display stats, not a real party member
 * with HP that can change. The bed's "full heal" is dialogue-only for
 * the same reason: no HP/SP system exists yet to heal.
 *
 * Sprites: sprites.h is generated by tools/gen_sprites.py from
 * xenodorian/CryMon's public/sprites/max/{down,up,left,right}-1.png
 * (max is the protagonist, per data.lua's dialogue lines -- e.g. the
 * bed/shelf/crate TALK entries this room's interact lines are drawn
 * from all use speaker = "max"; mason is a separate rival NPC met
 * later, per data.TALK.masonFight, not used here) and
 * public/sprites/props/{bed-father,bed-empty,shelf,
 * crate}.png -- the reference game's real pixel art, not placeholder
 * art. The bed-father prop art depicts the room's unnamed sick
 * father (data.TALK.father), distinct from both max and mason.
 */

#include <stdint.h>

typedef unsigned char  u8;
typedef unsigned short u16;
typedef unsigned int   u32;

#include "sprites.h"

#define PVR_BASE 0xa05f8000u
#define PVR(reg) (*(volatile u32 *)(PVR_BASE + (reg)))

#define PVR_BORDER_COLOR     0x040
#define PVR_FB_CFG_1         0x044
#define PVR_FB_CFG_2         0x048
#define PVR_RENDER_MODULO    0x04c
#define PVR_FB_ADDR          0x050
#define PVR_FB_SIZE          0x05c
#define PVR_VPOS_IRQ         0x0cc
#define PVR_IL_CFG           0x0d0
#define PVR_BORDER_X         0x0d4
#define PVR_SCAN_CLK         0x0d8
#define PVR_BORDER_Y         0x0dc
#define PVR_VIDEO_CFG        0x0e8
#define PVR_BITMAP_X         0x0ec
#define PVR_BITMAP_Y         0x0f0
#define PVR_SYNC_STATUS      0x10c  /* bits 0-8: nonzero while in vblank */

#define SCREEN_W 320
#define SCREEN_H 240

/* Double buffering, pipelined: each iteration flips to show whatever
   was drawn into the back buffer *last* iteration, then draws the
   next frame into the buffer that just became hidden. This is the
   order a KallistiOS/Dreamcast homebrew community reference (a
   DCEmulation forum thread on KOS double buffering) describes as
   correct: wait_vblank() -> flip the already-drawn buffer into view
   -> only then draw the next frame. The single-buffer version tried
   before this made tearing worse, not better, since every redraw
   wrote directly into whatever the display was actively scanning;
   double buffering keeps drawing entirely off-screen, so only a
   correctly-timed flip is needed to avoid tearing.

   This requires drawing every frame unconditionally, not just when
   something changed: alternating buffers while only sometimes
   redrawing would show one buffer's fresh content and then the
   *other* buffer's stale content every other frame once movement
   stops, which is its own visible glitch. Redrawing every frame is
   safe here specifically because it only ever touches the hidden
   buffer -- it was only unsafe in the single-buffer version. */
#define FB_OFFSET0 0x000000u
#define FB_OFFSET1 0x040000u

static u32 fb_back_offset = FB_OFFSET1;
static volatile u16 *draw_fb = (volatile u16 *)(0xa5000000u + FB_OFFSET1);

static void fb_flip(void) {
    PVR(PVR_FB_ADDR) = fb_back_offset;
    fb_back_offset = (fb_back_offset == FB_OFFSET0) ? FB_OFFSET1 : FB_OFFSET0;
    draw_fb = (volatile u16 *)(0xa5000000u + fb_back_offset);
}

/* DM_320x240_NTSC timing parameters, from KallistiOS's vid_builtin table */
#define SCANLINES 262
#define CLOCKS    857
#define BITMAPX   164
#define BITMAPY   24
#define SCANINT1  21
#define SCANINT2  260
#define BORDERX1  141
#define BORDERX2  843
#define BORDERY1  24
#define BORDERY2  263

static void video_init(void) {
    PVR(PVR_VIDEO_CFG) = PVR(PVR_VIDEO_CFG) | 0x8u;
    PVR(PVR_FB_CFG_1)  = PVR(PVR_FB_CFG_1) & ~1u;

    PVR(PVR_BORDER_COLOR) = 0;

    PVR(PVR_FB_CFG_1) = (1u << 2);
    PVR(PVR_FB_CFG_2) = 1u | (1u << 3);

    PVR(PVR_RENDER_MODULO) = (SCREEN_W * 2) / 8;
    PVR(PVR_FB_ADDR) = 0;

    PVR(PVR_FB_SIZE) = (((SCREEN_W * 2) / 4) - 1)
                      | (1u << 20)
                      | ((SCREEN_H - 1u) << 10);

    PVR(PVR_VPOS_IRQ) = (SCANINT1 << 16) | SCANINT2;
    PVR(PVR_IL_CFG) = 0x100;

    PVR(PVR_BORDER_X) = (BORDERX1 << 16) | BORDERX2;
    PVR(PVR_BORDER_Y) = (BORDERY1 << 16) | BORDERY2;
    PVR(PVR_SCAN_CLK) = (SCANLINES << 16) | CLOCKS;

    PVR(PVR_VIDEO_CFG) = PVR(PVR_VIDEO_CFG) | 0x100u;

    PVR(PVR_BITMAP_X) = BITMAPX;
    PVR(PVR_BITMAP_Y) = (BITMAPY << 16) | BITMAPY;

    *(volatile u32 *)0xa0702c00 =
        (*(volatile u32 *)0xa0702c00 & 0xfffffcffu) | (3u << 8);

    PVR(PVR_VIDEO_CFG) = PVR(PVR_VIDEO_CFG) & ~0x8u;
    PVR(PVR_FB_CFG_1)  = PVR(PVR_FB_CFG_1) | 1u;
}

/* Checked against KallistiOS's own vid_waitvbl() (hardware/video.c):
   wait for vblank to start, then wait for it to end, so each call
   corresponds to exactly one fresh frame. */
static void wait_vblank(void) {
    while(!(PVR(PVR_SYNC_STATUS) & 0x01ffu))
        ;
    while(PVR(PVR_SYNC_STATUS) & 0x01ffu)
        ;
}

static void vram_clear(void) {
    u32 i;
    for(i = 0; i < (u32)SCREEN_W * SCREEN_H; i++)
        draw_fb[i] = 0x0000;
}

static void put_pixel(int x, int y, u16 color) {
    if(x < 0 || x >= SCREEN_W || y < 0 || y >= SCREEN_H)
        return;
    draw_fb[y * SCREEN_W + x] = color;
}

static void fill_rect(int x, int y, int w, int h, u16 color) {
    int px, py;
    for(py = y; py < y + h; py++)
        for(px = x; px < x + w; px++)
            put_pixel(px, py, color);
}

static u16 rgb565(u8 r, u8 g, u8 b) {
    return (u16)(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3));
}

/* Blits a w x h RGB565 sprite (see sprites.h) with its top-left
   corner at (x, y), skipping any pixel equal to SPRITE_KEY
   (color-keyed transparency -- the sprite has no separate alpha
   channel once baked into the array). */
static void blit_sprite(const u16 *px, int w, int h, int x, int y) {
    int sx, sy;
    for(sy = 0; sy < h; sy++) {
        for(sx = 0; sx < w; sx++) {
            u16 c = px[sy * w + sx];
            if(c != SPRITE_KEY)
                put_pixel(x + sx, y + sy, c);
        }
    }
}

/* ----------------------------------------------------------------------
 * Font: 8x8, 1bpp glyphs, A-Z + space. Bit 7 = leftmost pixel of each
 * row. Enough to render the interact-dialogue lines and the title
 * screen; text is upper-cased and punctuation-free by construction.
 * ---------------------------------------------------------------------- */
static const uint8_t font_AZ[26][8] = {
    /* A */ { 0b00111100, 0b01000010, 0b10000001, 0b10000001,
              0b11111111, 0b10000001, 0b10000001, 0b00000000 },
    /* B */ { 0b11111100, 0b10000010, 0b10000010, 0b11111100,
              0b10000010, 0b10000010, 0b11111100, 0b00000000 },
    /* C */ { 0b01111110, 0b10000000, 0b10000000, 0b10000000,
              0b10000000, 0b10000000, 0b01111110, 0b00000000 },
    /* D */ { 0b11111100, 0b10000010, 0b10000001, 0b10000001,
              0b10000001, 0b10000010, 0b11111100, 0b00000000 },
    /* E */ { 0b11111111, 0b10000000, 0b10000000, 0b11111100,
              0b10000000, 0b10000000, 0b11111111, 0b00000000 },
    /* F */ { 0b11111111, 0b10000000, 0b10000000, 0b11111100,
              0b10000000, 0b10000000, 0b10000000, 0b00000000 },
    /* G */ { 0b01111110, 0b10000000, 0b10000000, 0b10001111,
              0b10000001, 0b10000001, 0b01111110, 0b00000000 },
    /* H */ { 0b10000001, 0b10000001, 0b10000001, 0b11111111,
              0b10000001, 0b10000001, 0b10000001, 0b00000000 },
    /* I */ { 0b11111111, 0b00011000, 0b00011000, 0b00011000,
              0b00011000, 0b00011000, 0b11111111, 0b00000000 },
    /* J */ { 0b00000111, 0b00000010, 0b00000010, 0b00000010,
              0b10000010, 0b10000010, 0b01111100, 0b00000000 },
    /* K */ { 0b10000010, 0b10000100, 0b10001000, 0b11110000,
              0b10001000, 0b10000100, 0b10000010, 0b00000000 },
    /* L */ { 0b10000000, 0b10000000, 0b10000000, 0b10000000,
              0b10000000, 0b10000000, 0b11111111, 0b00000000 },
    /* M */ { 0b10000001, 0b11000011, 0b10100101, 0b10011001,
              0b10000001, 0b10000001, 0b10000001, 0b00000000 },
    /* N */ { 0b10000001, 0b11000001, 0b10100001, 0b10010001,
              0b10001001, 0b10000101, 0b10000011, 0b00000000 },
    /* O */ { 0b01111110, 0b10000001, 0b10000001, 0b10000001,
              0b10000001, 0b10000001, 0b01111110, 0b00000000 },
    /* P */ { 0b11111100, 0b10000010, 0b10000010, 0b11111100,
              0b10000000, 0b10000000, 0b10000000, 0b00000000 },
    /* Q */ { 0b01111110, 0b10000001, 0b10000001, 0b10000001,
              0b10010101, 0b10001001, 0b01110110, 0b00000000 },
    /* R */ { 0b11111110, 0b10000001, 0b10000001, 0b11111110,
              0b10010000, 0b10001000, 0b10000100, 0b00000000 },
    /* S */ { 0b01111110, 0b10000000, 0b10000000, 0b01111100,
              0b00000010, 0b00000010, 0b11111100, 0b00000000 },
    /* T */ { 0b11111111, 0b00011000, 0b00011000, 0b00011000,
              0b00011000, 0b00011000, 0b00011000, 0b00000000 },
    /* U */ { 0b10000001, 0b10000001, 0b10000001, 0b10000001,
              0b10000001, 0b10000001, 0b01111110, 0b00000000 },
    /* V */ { 0b10000001, 0b10000001, 0b10000001, 0b01000010,
              0b01000010, 0b00100100, 0b00011000, 0b00000000 },
    /* W */ { 0b10000001, 0b10000001, 0b10000001, 0b10100101,
              0b10100101, 0b11011011, 0b10000001, 0b00000000 },
    /* X */ { 0b10000001, 0b01000010, 0b00100100, 0b00011000,
              0b00100100, 0b01000010, 0b10000001, 0b00000000 },
    /* Y */ { 0b10000001, 0b01000010, 0b00100100, 0b00011000,
              0b00011000, 0b00011000, 0b00011000, 0b00000000 },
    /* Z */ { 0b11111111, 0b00000010, 0b00000100, 0b00001000,
              0b00010000, 0b00100000, 0b11111111, 0b00000000 },
};

/* Digits 0-9, same style/size as font_AZ. Needed for the room's HUD
   (Quillpup's level, the bandage count) -- nothing in the dialogue
   text itself uses digits. */
static const uint8_t font_09[10][8] = {
    /* 0 */ { 0b00111100, 0b01100110, 0b01101110, 0b01110110,
              0b01100110, 0b01100110, 0b00111100, 0b00000000 },
    /* 1 */ { 0b00011000, 0b00111000, 0b00011000, 0b00011000,
              0b00011000, 0b00011000, 0b01111110, 0b00000000 },
    /* 2 */ { 0b00111100, 0b01100110, 0b00000110, 0b00001100,
              0b00011000, 0b00110000, 0b01111110, 0b00000000 },
    /* 3 */ { 0b00111100, 0b01100110, 0b00000110, 0b00011100,
              0b00000110, 0b01100110, 0b00111100, 0b00000000 },
    /* 4 */ { 0b00001100, 0b00011100, 0b00101100, 0b01001100,
              0b01111110, 0b00001100, 0b00001100, 0b00000000 },
    /* 5 */ { 0b01111110, 0b01100000, 0b01111100, 0b00000110,
              0b00000110, 0b01100110, 0b00111100, 0b00000000 },
    /* 6 */ { 0b00011100, 0b00110000, 0b01100000, 0b01111100,
              0b01100110, 0b01100110, 0b00111100, 0b00000000 },
    /* 7 */ { 0b01111110, 0b00000110, 0b00001100, 0b00011000,
              0b00110000, 0b00110000, 0b00110000, 0b00000000 },
    /* 8 */ { 0b00111100, 0b01100110, 0b01100110, 0b00111100,
              0b01100110, 0b01100110, 0b00111100, 0b00000000 },
    /* 9 */ { 0b00111100, 0b01100110, 0b01100110, 0b00111110,
              0b00000110, 0b00001100, 0b00111000, 0b00000000 },
};

static void draw_glyph(int ox, int oy, const uint8_t bitmap[8], u16 color, int scale) {
    int row, col, sx, sy;

    for(row = 0; row < 8; row++) {
        uint8_t bits = bitmap[row];

        for(col = 0; col < 8; col++) {
            if(!(bits & (0x80 >> col)))
                continue;

            for(sy = 0; sy < scale; sy++)
                for(sx = 0; sx < scale; sx++)
                    put_pixel(ox + col * scale + sx, oy + row * scale + sy, color);
        }
    }
}

static void draw_text_s(const char *s, int x, int y, u16 color, int scale) {
    int cx = x;
    int px = 8 * scale;
    for(; *s; s++) {
        if(*s >= 'A' && *s <= 'Z')
            draw_glyph(cx, y, font_AZ[*s - 'A'], color, scale);
        else if(*s >= '0' && *s <= '9')
            draw_glyph(cx, y, font_09[*s - '0'], color, scale);
        cx += px;
    }
}

static int text_width_s(const char *s, int scale) {
    int n = 0;
    for(; *s; s++) n++;
    return n * 8 * scale;
}

static void draw_text_center_s(const char *s, int cx, int y, u16 color, int scale) {
    draw_text_s(s, cx - text_width_s(s, scale) / 2, y, color, scale);
}

static int word_len(const char *s) {
    int n = 0;
    while(s[n] && s[n] != ' ')
        n++;
    return n;
}

/* Word-wraps s (space-separated, uppercase-and-punctuation-free like
   every TALK string below) into lines of at most max_chars columns,
   greedily packing words, and draws each line left-aligned at x
   starting at y with line_h pixels between line tops. Used for the
   dialogue box, whose longest ported line (data.TALK.shelf's second
   beat) wraps to exactly 3 lines -- the box is sized for that. */
#define WRAP_BUF_MAX 40
static void draw_wrapped(const char *s, int x, int y, u16 color, int scale,
                          int max_chars, int line_h) {
    char buf[WRAP_BUF_MAX + 1];
    int buf_len = 0;
    int line = 0;
    const char *p = s;

    for(;;) {
        int wlen = word_len(p);
        int need = wlen + (buf_len > 0 ? 1 : 0);

        if(buf_len > 0 && buf_len + need > max_chars) {
            buf[buf_len] = 0;
            draw_text_s(buf, x, y + line * line_h, color, scale);
            line++;
            buf_len = 0;
        }

        if(buf_len > 0)
            buf[buf_len++] = ' ';
        {
            int i;
            for(i = 0; i < wlen && buf_len < WRAP_BUF_MAX; i++)
                buf[buf_len++] = p[i];
        }

        p += wlen;
        if(*p != ' ')
            break;
        p++;
    }

    buf[buf_len] = 0;
    draw_text_s(buf, x, y + line * line_h, color, scale);
}

/* ----------------------------------------------------------------------
 * Tiny manual string building for the HUD/bag/party rows below (no
 * libc here -- nostdlib/ffreestanding). s_cat/s_cat_uint append to a
 * caller-owned buffer and return the new length; callers chain them
 * to build one row's text before a single draw_text_s call.
 * ---------------------------------------------------------------------- */
static int s_cat(char *dst, int len, const char *src) {
    while(*src)
        dst[len++] = *src++;
    return len;
}

static int s_cat_uint(char *dst, int len, int v) {
    char tmp[6];
    int n = 0;
    if(v == 0) {
        dst[len++] = '0';
        return len;
    }
    while(v > 0 && n < 6) {
        tmp[n++] = (char)('0' + (v % 10));
        v /= 10;
    }
    while(n > 0)
        dst[len++] = tmp[--n];
    return len;
}

#define TITLE_SCALE 3
#define DIALOGUE_SCALE 1

static void draw_press_start(void) {
    vram_clear();
    draw_text_center_s("PRESS START", SCREEN_W / 2,
                        SCREEN_H / 2 - 4 * TITLE_SCALE, 0xFFFF, TITLE_SCALE);
}

/* ----------------------------------------------------------------------
 * Minimal Maple bus controller driver (port A / unit 0 only). Same
 * derivation as hello-world-dreamcast/src/hello.c -- see that file for
 * the full explanation of the register layout and packet format,
 * checked against KallistiOS's own Maple driver source.
 * ---------------------------------------------------------------------- */
#define MAPLE_BASE      0xa05f6c00u
#define MAPLE_DMA_ADDR  (*(volatile u32 *)(MAPLE_BASE + 0x04))
#define MAPLE_DMA_TSEL  (*(volatile u32 *)(MAPLE_BASE + 0x10))
#define MAPLE_ENABLE    (*(volatile u32 *)(MAPLE_BASE + 0x14))
#define MAPLE_STATE     (*(volatile u32 *)(MAPLE_BASE + 0x18))
#define MAPLE_SPEED     (*(volatile u32 *)(MAPLE_BASE + 0x80))
#define MAPLE_DMA_PROT  (*(volatile u32 *)(MAPLE_BASE + 0x8c))

#define MAPLE_COMMAND_GETCOND   9
#define MAPLE_RESPONSE_DATATRF  8
#define MAPLE_FUNC_CONTROLLER   0x01000000u

#define CONT_C            (1u << 0)
#define CONT_B            (1u << 1)
#define CONT_A            (1u << 2)
#define CONT_START        (1u << 3)
#define CONT_DPAD_UP      (1u << 4)
#define CONT_DPAD_DOWN    (1u << 5)
#define CONT_DPAD_LEFT    (1u << 6)
#define CONT_DPAD_RIGHT   (1u << 7)
#define CONT_Z            (1u << 8)
#define CONT_Y            (1u << 9)
#define CONT_X            (1u << 10)

static u32 maple_cmd_buf[8]  __attribute__((aligned(32)));
static u32 maple_resp_buf[64] __attribute__((aligned(32)));

#define P2(p)   ((volatile u32 *)(((u32)(p)) | 0x20000000u))
#define PHYS(p) (((u32)(p)) & 0x1fffffffu)

static void maple_init(void) {
    MAPLE_DMA_PROT = 0x6155404fu;
    MAPLE_DMA_TSEL = 0;
    MAPLE_SPEED = 0x0000u | (50000u << 16);
    MAPLE_ENABLE = 1;
}

static u16 maple_poll_buttons(void) {
    volatile u32 *cmd  = P2(maple_cmd_buf);
    volatile u32 *resp = P2(maple_resp_buf);
    u32 timeout;

    cmd[0] = 1u | (0u << 16) | 0x80000000u;
    cmd[1] = PHYS(maple_resp_buf);
    cmd[2] = MAPLE_COMMAND_GETCOND | (0x20u << 8) | (0u << 16) | (1u << 24);
    cmd[3] = MAPLE_FUNC_CONTROLLER;

    MAPLE_DMA_ADDR = PHYS(maple_cmd_buf);
    MAPLE_STATE = 1;

    for(timeout = 0; timeout < 2000000u; timeout++) {
        if(MAPLE_STATE == 0)
            break;
    }
    if(MAPLE_STATE != 0)
        return 0xffff;

    if((resp[0] & 0xffu) != MAPLE_RESPONSE_DATATRF)
        return 0xffff;
    if(resp[1] != MAPLE_FUNC_CONTROLLER)
        return 0xffff;

    return (u16)(resp[2] & 0xffffu);
}

static int pressed(u16 raw, u16 mask) {
    return (raw & mask) == 0;
}

/* ----------------------------------------------------------------------
 * The world: all 4 maps, verbatim from CryMon's love/game/src/data.lua
 * (data.HOUSE/VELD/FOREST/GROVE), data.isSolidTile (SOLID_SET), and
 * love/game/src/draw.lua (paintTile). 32px tiles in the original,
 * drawn here at 20px (matching every earlier step); VELD/FOREST/GROVE
 * are much bigger than the 320x240 screen, so this step adds camera
 * scrolling (compute_camera below) -- HOUSE still ends up centered
 * exactly like before, since a map smaller than the screen just gets
 * a centered (possibly negative) camera offset.
 *
 * GROVE's mid-map 'D' row (data.lua splits the Cathleen half from the
 * Shinigami half, opened only after Cathleen is caught) is walkable
 * here rather than gated: no cathCaught state exists yet (that's
 * battle/catching, a later milestone), and the reference project's
 * own data.lua notes that native/crymon.c already ships this same
 * simplification, so it's a documented, precedented deferral rather
 * than a new gap.
 * ---------------------------------------------------------------------- */
#define TILE 20

#define MAP_HOUSE  0
#define MAP_VELD   1
#define MAP_FOREST 2
#define MAP_GROVE  3

typedef struct {
    const char *const *rows;
    int cols, rows_n;
} Map;

static const char *const map_house_rows[] = {
    "HHHHHHHHHHHHHH",
    "HFFFFFFFFFFFFH",
    "HFFFFFFFFFFFFH",
    "HFFFFFFFFFFFFH",
    "HFBFFFFSFFFCFH",
    "HFFFFFFFFFFFFH",
    "HUFFFFFFFFFFFH",
    "HFFFFPFFFFFFFH",
    "HFFFFFFFFFFFFH",
    "HFFFFFFFFFFFFH",
    "HHHHHHDHHHHHHH",
};

static const char *const map_veld_rows[] = {
    "##############################",
    "####..........RRRR..........##",
    "##.Q.^^.......HHHH......WWW.##",
    "##............HDH......WWA..##",
    "##..K.........===...I...W....#",
    "##...TTT.....=====.....TTT..G#",
    "##...TTT....===,===....TTT...#",
    "##....M......=====....**.....#",
    "##.V.TTT......===......TTT...#",
    "##............===............#",
    "###....X...J.=====...........#",
    "##...TTT......===............#",
    "##............===.......L....#",
    "##...TTT.....=====......TTT..#",
    "##............===......^^....#",
    "##....TTT....=====......TTT..#",
    "##....TTT.....===......TTT...#",
    "##............===............#",
    "##...........=====.....NNNN..#",
    "##............===.......NE...#",
    "###...........===...........##",
    "#############=Z=##############",
};

static const char *const map_forest_rows[] = {
    "##########################",
    "####.........Y.........###",
    "###.........===.........##",
    "##...TTT....===....TTT..##",
    "##...TTT...=====...TTT..##",
    "##.1........===.......2.##",
    "##...TTT....===....TTT..##",
    "##..........=====.......##",
    "##...TTT....===....TTT..##",
    "##...........===........##",
    "##...TTT....=====..TTT..##",
    "##...........===........##",
    "##...TTT.....===...TTT..##",
    "##...........=====......##",
    "##....TTT....===...TTT..##",
    "##............===.......##",
    "##...TTT......===..TTT..##",
    "##............===....3..##",
    "###...........===......###",
    "#############=O=##########",
};

static const char *const map_grove_rows[] = {
    "##########################",
    "####.........O.........###",
    "###.........===.........##",
    "##..........===.........##",
    "##.........=====........##",
    "##..........===.........##",
    "##.........=====........##",
    "##..........===.........##",
    "##.........=====........##",
    "##..........===.........##",
    "##........=======.......##",
    "##........===8===.......##",
    "##........=======.......##",
    "#############D############",
    "##.........=====........##",
    "##..........===.........##",
    "##.........=====........##",
    "##..........===.........##",
    "##...........9..........##",
    "###....................###",
    "##########################",
};

static const Map MAPS[4] = {
    { map_house_rows,  14, 11 },
    { map_veld_rows,   30, 22 },
    { map_forest_rows, 26, 20 },
    { map_grove_rows,  26, 21 },
};

/* data.lua's SOLID_SET, verbatim: "#HWRBC^NKEVAQXUJI". D (door), S
   (shelf) and the digit/letter NPC marks are deliberately absent --
   doors must be walkable to trigger a warp, and marks are interacted
   with by proximity, not blocked by collision. */
static int tile_is_solid(char ch) {
    static const char *const solid = "#HWRBC^NKEVAQXUJI";
    const char *p;
    for(p = solid; *p; p++)
        if(*p == ch)
            return 1;
    return 0;
}

/* Out-of-bounds tiles read as '#' (solid), matching data.tileAt. */
static char tile_at(int map_id, int col, int row) {
    const Map *m = &MAPS[map_id];
    if(col < 0 || col >= m->cols || row < 0 || row >= m->rows_n)
        return '#';
    return m->rows[row][col];
}

/* First occurrence of mark, row-major, matching data.spawnOf's
   row:find() scan order. Every call site below only asks for marks
   known to exist on that map (checked against the grids above), so
   the not-found fallback is never actually hit in practice. */
static void find_mark(int map_id, char mark, int *out_col, int *out_row) {
    const Map *m = &MAPS[map_id];
    int row, col;
    for(row = 0; row < m->rows_n; row++) {
        for(col = 0; col < m->cols; col++) {
            if(m->rows[row][col] == mark) {
                *out_col = col;
                *out_row = row;
                return;
            }
        }
    }
    *out_col = 2;
    *out_row = 2;
}

static void mark_center(int map_id, char mark, int *out_x, int *out_y) {
    int col, row;
    find_mark(map_id, mark, &col, &row);
    *out_x = col * TILE + TILE / 2;
    *out_y = row * TILE + TILE / 2;
}

/* draw.lua's paintTile, verbatim palette (including its two-rect
   detail tiles: grass speckle '.', tree 'T', forest-floor '#', flower
   '*'). Tile chars not explicitly listed (every NPC/prop mark, plus
   VELD/FOREST/GROVE decoration letters not ported to real props
   here) fall through to paintTile's own grass-green default. */
static void draw_tile(char ch, int dx, int dy) {
    int t = TILE;

    switch(ch) {
        case 'H':
            fill_rect(dx, dy, t, t, rgb565(42, 30, 22));
            return;
        case 'R':
            fill_rect(dx, dy, t, t, rgb565(106, 64, 48));
            return;
        case 'F':
        case 'P':
            fill_rect(dx, dy, t, t, rgb565(106, 82, 56));
            return;
        case 'D':
            fill_rect(dx, dy, t, t, rgb565(26, 18, 12));
            return;
        case 'B':
        case 'U':
        case 'C':
        case 'S':
            fill_rect(dx, dy, t, t, rgb565(106, 82, 56));
            return;
        case '.':
            fill_rect(dx, dy, t, t, rgb565(61, 90, 56));
            fill_rect(dx + 3, dy + 4, 1, 1, rgb565(90, 122, 82));
            return;
        case 'T':
            fill_rect(dx, dy, t, t, rgb565(47, 74, 44));
            fill_rect(dx + 4, dy + 3, 3, 15, rgb565(106, 138, 58));
            fill_rect(dx + 10, dy + 1, 3, 16, rgb565(90, 122, 82));
            return;
        case '=':
        case 'Z':
        case 'Y':
        case '3':
        case 'O':
        case '8':
        case '9':
            fill_rect(dx, dy, t, t, rgb565(107, 90, 58));
            return;
        case ',':
            fill_rect(dx, dy, t, t, rgb565(90, 74, 58));
            return;
        case '#':
            fill_rect(dx, dy, t, t, rgb565(28, 36, 24));
            fill_rect(dx + 3, dy + 1, 15, 11, rgb565(61, 90, 56));
            return;
        case 'W':
            fill_rect(dx, dy, t, t, rgb565(42, 58, 68));
            return;
        case '^':
            fill_rect(dx, dy, t, t, rgb565(74, 64, 48));
            return;
        case 'N':
        case 'E':
            fill_rect(dx, dy, t, t, rgb565(90, 70, 48));
            return;
        case '*':
            fill_rect(dx, dy, t, t, rgb565(61, 90, 56));
            fill_rect(dx + 8, dy + 8, 4, 4, rgb565(180, 60, 80));
            return;
        default:
            fill_rect(dx, dy, t, t, rgb565(61, 90, 56));
            return;
    }
}

/* Keeps the player roughly centered, clamped to the map's edges; a
   map no bigger than the screen (HOUSE) instead gets a fixed,
   centered offset (possibly negative), which is what actually
   produces the letterboxed look the old HOUSE-only code hardcoded --
   a tile drawn at col*TILE - cam_x still lands in the right place
   when cam_x is negative. */
static void compute_camera(int map_id, int px, int py, int *cam_x, int *cam_y) {
    const Map *m = &MAPS[map_id];
    int mw = m->cols * TILE, mh = m->rows_n * TILE;
    int cx, cy;

    if(mw <= SCREEN_W) {
        cx = (mw - SCREEN_W) / 2;
    }
    else {
        cx = px - SCREEN_W / 2;
        if(cx < 0) cx = 0;
        if(cx > mw - SCREEN_W) cx = mw - SCREEN_W;
    }

    if(mh <= SCREEN_H) {
        cy = (mh - SCREEN_H) / 2;
    }
    else {
        cy = py - SCREEN_H / 2;
        if(cy < 0) cy = 0;
        if(cy > mh - SCREEN_H) cy = mh - SCREEN_H;
    }

    *cam_x = cx;
    *cam_y = cy;
}

/* Draws only the tile range that can be visible at this camera
   offset -- VELD alone is 30x22 = 660 tiles, too many to redraw
   in full every frame at 20px/tile through put_pixel. */
static void draw_map(int map_id, int cam_x, int cam_y) {
    const Map *m = &MAPS[map_id];
    int col0 = cam_x / TILE;
    int col1 = (cam_x + SCREEN_W) / TILE + 1;
    int row0 = cam_y / TILE;
    int row1 = (cam_y + SCREEN_H) / TILE + 1;
    int row, col;

    if(col0 < 0) col0 = 0;
    if(row0 < 0) row0 = 0;
    if(col1 > m->cols) col1 = m->cols;
    if(row1 > m->rows_n) row1 = m->rows_n;

    /* Letterboxed maps (HOUSE) leave a border the tile loop below
       never touches, so it needs clearing or it'd show whatever was
       drawn there previously (e.g. the title screen text). */
    vram_clear();

    for(row = row0; row < row1; row++)
        for(col = col0; col < col1; col++)
            draw_tile(m->rows[row][col], col * TILE - cam_x, row * TILE - cam_y);
}

/* Props are center-anchored on their mark's tile center, matching the
   flat-rect placeholders this replaced in an earlier step. Sizes come
   from sprites.h (the real art's own dimensions, downscaled by
   gen_sprites.py -- not the original 32px-tile-space sizes from
   render.lua, which didn't match the actual art's proportions
   anyway). HOUSE-only: B/U/S/C don't appear on any other map. */
static void draw_prop(char mark, const u16 *px, int w, int h, int cam_x, int cam_y) {
    int cx, cy;
    mark_center(MAP_HOUSE, mark, &cx, &cy);
    blit_sprite(px, w, h, cx - cam_x - w / 2, cy - cam_y - h / 2);
}

static void draw_props(int map_id, int cam_x, int cam_y) {
    if(map_id != MAP_HOUSE)
        return;
    draw_prop('B', prop_bed_father, PROP_BED_FATHER_W, PROP_BED_FATHER_H, cam_x, cam_y);
    draw_prop('U', prop_bed_empty, PROP_BED_EMPTY_W, PROP_BED_EMPTY_H, cam_x, cam_y);
    draw_prop('S', prop_shelf, PROP_SHELF_W, PROP_SHELF_H, cam_x, cam_y);
    draw_prop('C', prop_crate, PROP_CRATE_W, PROP_CRATE_H, cam_x, cam_y);
}

/* Player sprite, bottom-center anchored at (cx, cy) same as the
   silhouette this replaces (draw.lua's draw.actor() used the same
   anchor). dir matches the sprite arrays below: 0=down,1=up,2=left,
   3=right. */
static void draw_player(int cx, int cy, int dir) {
    static const u16 *const frames[4] = {
        max_down, max_up, max_left, max_right
    };
    int x = cx - MAX_SPRITE_W / 2, y = cy - MAX_SPRITE_H;
    blit_sprite(frames[dir], MAX_SPRITE_W, MAX_SPRITE_H, x, y);
}

/* ----------------------------------------------------------------------
 * Interact dialogue: full multi-beat sequences from data.TALK.father /
 * fatherAfter / bed / shelf / shelfEmpty / crate / crateEmpty
 * (love/game/src/data.lua), verbatim except upper-cased and stripped
 * of punctuation our A-Z/0-9-only font can't render. Each sequence is
 * shown one beat per A-press (matching sayn()'s one-beat-per-advance
 * in the reference), word-wrapped into the dialogue box.
 * ---------------------------------------------------------------------- */
static const char *const TALK_FATHER[] = {
    "THERES A WAR CRYTOWN IS ALREADY BLEEDING",
    "YOURE TOO SICK TO DEFEND IT FROM THE SOLDIERS I KNOW THAT",
    "SO IM STEALING YOUR CRYMON",
    "FATHER DOES NOT WAKE THE CAPTURE CRYSTAL IS STILL ON THE SHELF",
};
static const char *const TALK_FATHER_AFTER[] = {
    "I ALREADY TOOK QUILLPUP SLEEP ILL DO THE FIGHTING",
    "HIS BREATH IS THIN HE DOES NOT ANSWER",
};
static const char *const TALK_BED[] = {
    "JUST UNTIL THEY BREATHE AGAIN",
    "MAXS EMPTY BED THE CRYMON SLEEP CUTS CLOSE SPECIALS RETURN",
};
static const char *const TALK_SHELF[] = {
    "THIS IS IT FATHERS CRYSTAL QUILLPUP IS INSIDE",
    "THE CRYSTAL BREAKS WARM IN HER HANDS QUILLPUP SHAKES OUT ONTO THE FLOORBOARDS",
    "YOURE COMING CRYTOWN DOESNT GET TO FALL",
};
static const char *const TALK_SHELF_EMPTY[] = {
    "DUST THE CRYSTAL IS ALREADY OPEN",
};
static const char *const TALK_CRATE[] = {
    "A WRAP HE WONT MISS IT",
    "A LINEN WRAP UNDER THE LID YOU TAKE IT",
};
static const char *const TALK_CRATE_EMPTY[] = {
    "SPLINTERS AND A MOTH EMPTY",
};

/* Door/warp flavor lines, data.TALK.doorLocked/doorOut/cottage/
   forestEnter/forestLeave/groveEnter/groveLeave. doorOut's original
   also kicks off the Mason NPC encounter (masonPh) the first time you
   leave the house; that's NPC/battle content not built yet, so this
   step always shows doorOut's plain flavor text instead. */
static const char *const TALK_DOOR_LOCKED[] = {
    "NOT YET FATHERS CRYMON IS STILL ON THE SHELF",
};
static const char *const TALK_DOOR_OUT[] = {
    "NIGHT AIR I CAN DO THIS",
    "TALL GRASS HIDES CRYMON WREN WEST POND EAST BRAM ON THE PATH CALDER SOUTH",
};
static const char *const TALK_COTTAGE[] = {
    "THE COTTAGE FATHER IN THE BED MY BED SOUTH DOOR LEAVES",
};
static const char *const TALK_FOREST_ENTER[] = {
    "THE TREES CLOSE OVER THE PATH",
    "TALL GRASS PATROLS IF THEY SEE YOU THEY WILL COME THE PATH KEEPS SOUTH",
};
static const char *const TALK_FOREST_LEAVE[] = {
    "BACK TOWARD THE COTTAGE PATH",
};
static const char *const TALK_GROVE_ENTER[] = {
    "THE GRASS DIES OUT STONE AND HUSH",
    "NO TALL GRASS SOMETHING WAITS ON THE PATH",
};
static const char *const TALK_GROVE_LEAVE[] = {
    "BACK UNDER THE TREES",
};

#define TALK_LEN(arr) (int)(sizeof(arr) / sizeof((arr)[0]))

#define DIALOGUE_MAX_CHARS 37
#define DIALOGUE_LINE_H    9

static void draw_dialogue_box(const char *line) {
    fill_rect(4, SCREEN_H - 44, SCREEN_W - 8, 40, rgb565(18, 17, 14));
    fill_rect(4, SCREEN_H - 44, SCREEN_W - 8, 2, rgb565(197, 206, 198));
    fill_rect(4, SCREEN_H - 6, SCREEN_W - 8, 2, rgb565(197, 206, 198));
    draw_wrapped(line, 12, SCREEN_H - 38, rgb565(232, 228, 216), DIALOGUE_SCALE,
                 DIALOGUE_MAX_CHARS, DIALOGUE_LINE_H);
}

/* Small HUD in the screen's top-left corner (fixed there regardless
   of camera position), showing what interacting has granted so far
   -- there's no inventory/party HUD overlay in the reference, but
   there's also no way to see this port's bag/party menus without
   opening them, so this stays as a quick-glance confirmation. */
static void draw_hud(int got_shelf, int looted_crate, int bag_bandage) {
    int y = 2;

    if(got_shelf) {
        const char *label = "QUILLPUP LV";
        draw_text_s(label, 4, y, 0xFFFF, DIALOGUE_SCALE);
        draw_glyph(4 + text_width_s(label, DIALOGUE_SCALE), y,
                   font_09[3], 0xFFFF, DIALOGUE_SCALE);
        y += DIALOGUE_LINE_H;
    }
    if(looted_crate) {
        const char *label = "BANDAGE X";
        draw_text_s(label, 4, y, 0xFFFF, DIALOGUE_SCALE);
        draw_glyph(4 + text_width_s(label, DIALOGUE_SCALE), y,
                   font_09[bag_bandage % 10], 0xFFFF, DIALOGUE_SCALE);
    }
}

/* ----------------------------------------------------------------------
 * Bag and party menus, ported from render.lua's drawBag()/drawParty().
 * Both are read-only overlays here (no item use, no lead-switching --
 * nothing in this room's scope needs either yet): open with Y (bag) or
 * START (party), close with B. data.lua's START_BAG gives the room's
 * starting counts (salve 2, bandage 2, bitterroot 1, dust 1, gem 0)
 * and START_MARKS (16); the bandage count is the only one this room
 * ever changes (the crate). Item icons (render.lua's "item-<id>"
 * sprites) aren't ported -- text rows only, like the rest of this
 * step's UI.
 * ---------------------------------------------------------------------- */
typedef struct {
    int salve, bandage, bitterroot, dust, gem;
} Bag;

#define MARKS_START 16

#define MENU_X 20
#define MENU_Y 20
#define MENU_W (SCREEN_W - 2 * MENU_X)
#define MENU_H (SCREEN_H - 2 * MENU_Y)
#define MENU_SCALE 1
#define MENU_ROW_H 16

static void draw_menu_frame(const char *title) {
    fill_rect(MENU_X, MENU_Y, MENU_W, MENU_H, rgb565(18, 17, 14));
    fill_rect(MENU_X, MENU_Y, MENU_W, 2, rgb565(197, 206, 198));
    fill_rect(MENU_X, MENU_Y + MENU_H - 2, MENU_W, 2, rgb565(197, 206, 198));
    draw_text_s(title, MENU_X + 8, MENU_Y + 8, rgb565(197, 206, 198), MENU_SCALE);
    draw_text_s("B CLOSE", MENU_X + 8, MENU_Y + MENU_H - 16,
                rgb565(90, 122, 82), MENU_SCALE);
}

static void draw_bag_row(const char *label, int count, int y) {
    char buf[32];
    int n = s_cat(buf, 0, label);
    n = s_cat(buf, n, " X");
    n = s_cat_uint(buf, n, count);
    buf[n] = 0;
    draw_text_s(buf, MENU_X + 8, y, rgb565(232, 228, 216), MENU_SCALE);
}

static void draw_bag_menu(const Bag *bag) {
    int y = MENU_Y + 24;
    char marks_buf[16];
    int n;

    draw_menu_frame("BAG");

    n = s_cat(marks_buf, 0, "MARKS ");
    n = s_cat_uint(marks_buf, n, MARKS_START);
    marks_buf[n] = 0;
    draw_text_s(marks_buf, MENU_X + MENU_W - 8 - text_width_s(marks_buf, MENU_SCALE),
                MENU_Y + 8, rgb565(143, 74, 64), MENU_SCALE);

    draw_bag_row("MOSS SALVE", bag->salve, y);       y += MENU_ROW_H;
    draw_bag_row("LINEN WRAP", bag->bandage, y);     y += MENU_ROW_H;
    draw_bag_row("BITTERROOT", bag->bitterroot, y);  y += MENU_ROW_H;
    draw_bag_row("ASH DUST", bag->dust, y);          y += MENU_ROW_H;
    draw_bag_row("CAPTURE CRYSTAL", bag->gem, y);
}

/* Quillpup's stats at the level this room mints it (mintMonster's
   growth curve: g = 1 + (lv-3)*0.12, so lv 3 gives g == 1 exactly --
   maxHp = floor(34*1 + 0.5) = 34, matching data.lua's quillpup
   species entry). No battle system exists yet to change hp from
   maxHp, so it's shown here as always full. */
#define QUILLPUP_LV     3
#define QUILLPUP_MAX_HP 34

static void draw_party_menu(int got_shelf) {
    int y = MENU_Y + 24;

    draw_menu_frame("CRYMON");

    if(got_shelf) {
        char buf[40];
        int n = s_cat(buf, 0, "> QUILLPUP LV");
        n = s_cat_uint(buf, n, QUILLPUP_LV);
        n = s_cat(buf, n, " HP ");
        n = s_cat_uint(buf, n, QUILLPUP_MAX_HP);
        n = s_cat(buf, n, "/");
        n = s_cat_uint(buf, n, QUILLPUP_MAX_HP);
        buf[n] = 0;
        draw_text_s(buf, MENU_X + 8, y, rgb565(232, 228, 216), MENU_SCALE);
    }
    else {
        draw_text_s("NO CRYMON YET", MENU_X + 8, y, rgb565(138, 134, 120), MENU_SCALE);
    }
}

/* interact() in state.lua: closest of U/B/S/C within a 36px radius
   (36*36=1296) in the original's 32px-tile space; scaled to our 20px
   tiles that's a 22.5px radius (22*22=484). */
/* HOUSE-only, matching interact()'s MAP_HOUSE branch -- callers only
   invoke this when map_id == MAP_HOUSE. */
static char closest_mark(int px, int py) {
    static const char marks[4] = { 'U', 'B', 'S', 'C' };
    int i;
    int best = 484, best_i = -1;

    for(i = 0; i < 4; i++) {
        int mx, my, dx, dy, d;
        mark_center(MAP_HOUSE, marks[i], &mx, &my);
        dx = px - mx;
        dy = py - my;
        d = dx * dx + dy * dy;
        if(d <= best) {
            best = d;
            best_i = i;
        }
    }
    return best_i >= 0 ? marks[best_i] : 0;
}

/* state.lua's warp(): places the player just past the destination
   mark, facing back the way they came (down if arriving from the
   south, up otherwise) -- matches doorLock's 20-frame cooldown below
   against instantly re-triggering the door tile on arrival. */
static void do_warp(int *map_id, int *px, int *py, int *pdir,
                     int to_map, char mark, int from_south) {
    int col, row, sx, sy;
    *map_id = to_map;
    find_mark(to_map, mark, &col, &row);
    sx = col * TILE + TILE / 2;
    sy = row * TILE + TILE / 2;
    *px = sx;
    *py = from_south ? (sy + TILE + 8) : (sy - TILE);
    *pdir = from_south ? 0 : 1;
}

void main(void) {
    int state = 0; /* 0 = title screen, 1 = starting room */
    int prev_start = 0, prev_a = 0, prev_b = 0, prev_y = 0;
    int map_id = MAP_HOUSE;
    int px, py, pdir = 0; /* dir: 0=down,1=up,2=left,3=right */
    int col, row;
    int cam_x, cam_y;
    u16 raw;
    int start_now, a_now, b_now, y_now;

    /* Frames left before a door tile can trigger another warp,
       matching state.lua's G.doorLock (set to 20 on spawn/warp,
       ticked down by 1 per world-state frame). */
    int door_lock = 0;

    /* Room state, matching state.lua's G.gotShelf / G.lootedCrate /
       G.bag (data.START_BAG). No HP/SP system exists yet, so the
       bed's "full heal" (state.lua's fullHeal()) has nothing to do
       here beyond showing its dialogue; no battle/party system
       exists yet either, so Quillpup is tracked only as the
       got_shelf flag plus the HUD/party-menu lines, not as a real
       party member. */
    int got_shelf = 0, looted_crate = 0;
    Bag bag = { 2, 2, 1, 1, 0 }; /* salve, bandage, bitterroot, dust, gem */

    /* 0 = no menu, 1 = bag, 2 = party. Opened from the world with Y /
       START (state.lua's selectPressed()/startPressed() -- there's no
       Select button on a Dreamcast pad, so Y stands in for it), closed
       with B (state.lua's cancelPressed(), which also accepts start
       and select; B alone is enough here since neither Y nor START
       need a second meaning while a menu is open). */
    int menu_mode = 0;

    /* Active dialogue sequence: seq_lines/seq_len name the current
       TALK_* array, seq_beat indexes into it. seq_lines == 0 means no
       dialogue is showing. */
    const char *const *seq_lines = 0;
    int seq_len = 0, seq_beat = 0;

    video_init();
    maple_init();

    find_mark(MAP_HOUSE, 'P', &col, &row);
    px = col * TILE + TILE / 2;
    py = row * TILE + TILE / 2;

    /* Prime both buffers with the title screen before the main loop
       starts flipping, so the first flip doesn't show whatever
       garbage was in VRAM at boot. */
    draw_press_start();
    fb_flip();
    draw_press_start();

    for(;;) {
        wait_vblank();
        fb_flip();

        raw = maple_poll_buttons();
        start_now = pressed(raw, CONT_START);
        a_now     = pressed(raw, CONT_A);
        b_now     = pressed(raw, CONT_B);
        y_now     = pressed(raw, CONT_Y);

        if(state == 0) {
            if(start_now && !prev_start)
                state = 1;
        }
        else if(menu_mode) {
            /* state.lua's MODE.BAG/MODE.PARTY update: only closing is
               handled, matching the reference (no cursor/use/swap
               logic in this port's scope). */
            if((b_now && !prev_b) || (start_now && !prev_start))
                menu_mode = 0;
        }
        else {
            /* Movement is frozen while a dialogue sequence is active,
               matching state.lua's MODE.TALK (movement there is only
               processed in MODE.WALK). */
            if(door_lock > 0)
                door_lock--;

            if(!seq_lines) {
                int dx = 0, dy = 0;
                int map_w = MAPS[map_id].cols * TILE;
                int map_h = MAPS[map_id].rows_n * TILE;

                if(pressed(raw, CONT_DPAD_LEFT))  { dx = -1; pdir = 2; }
                if(pressed(raw, CONT_DPAD_RIGHT)) { dx = 1;  pdir = 3; }
                if(pressed(raw, CONT_DPAD_UP))    { dy = -1; pdir = 1; }
                if(pressed(raw, CONT_DPAD_DOWN))  { dy = 1;  pdir = 0; }

                if(dx != 0 || dy != 0) {
                    /* Axis-separated movement so the player slides
                       along walls instead of stopping dead on a
                       diagonal. Half the collision box (6px) is
                       checked at the candidate feet position. */
                    int speed = 1; /* px/frame; ~60px/sec at 60fps,
                                       scaled down from the original's
                                       110px/sec at 32px tiles for our
                                       smaller tiles */
                    int nx = px + dx * speed;
                    int ny = py + dy * speed;

                    if(dx != 0 && !tile_is_solid(tile_at(map_id, (nx + (dx > 0 ? 6 : -6)) / TILE,
                                                          py / TILE))) {
                        px = nx;
                    }
                    if(dy != 0 && !tile_is_solid(tile_at(map_id, px / TILE,
                                                          (ny + (dy > 0 ? 6 : -6)) / TILE))) {
                        py = ny;
                    }

                    if(px < 8) px = 8;
                    if(px > map_w - 8) px = map_w - 8;
                    if(py < 8) py = 8;
                    if(py > map_h - 4) py = map_h - 4;
                }

                /* Door/warp tiles, matching state.lua's chain of
                   mapId/tile checks (doorLock gates it, same as the
                   reference). GROVE has no exit warp of its own in
                   this step -- data.lua's GROVE only defines the 'O'
                   entrance shared with FOREST, and the far side (past
                   Shinigami) is battle-gated content not built yet. */
                if(door_lock <= 0) {
                    char here = tile_at(map_id, px / TILE, py / TILE);

                    if(map_id == MAP_HOUSE && here == 'D') {
                        if(!got_shelf) {
                            find_mark(MAP_HOUSE, 'D', &col, &row);
                            py = row * TILE + TILE / 2 - TILE;
                            pdir = 1;
                            door_lock = 20;
                            seq_lines = TALK_DOOR_LOCKED;
                            seq_len = TALK_LEN(TALK_DOOR_LOCKED);
                            seq_beat = 0;
                        }
                        else {
                            do_warp(&map_id, &px, &py, &pdir, MAP_VELD, 'D', 1);
                            door_lock = 20;
                            seq_lines = TALK_DOOR_OUT;
                            seq_len = TALK_LEN(TALK_DOOR_OUT);
                            seq_beat = 0;
                        }
                    }
                    else if(map_id == MAP_VELD && here == 'D') {
                        do_warp(&map_id, &px, &py, &pdir, MAP_HOUSE, 'D', 0);
                        door_lock = 20;
                        seq_lines = TALK_COTTAGE;
                        seq_len = TALK_LEN(TALK_COTTAGE);
                        seq_beat = 0;
                    }
                    else if(map_id == MAP_VELD && here == 'Z') {
                        do_warp(&map_id, &px, &py, &pdir, MAP_FOREST, 'Y', 1);
                        door_lock = 20;
                        seq_lines = TALK_FOREST_ENTER;
                        seq_len = TALK_LEN(TALK_FOREST_ENTER);
                        seq_beat = 0;
                    }
                    else if(map_id == MAP_FOREST && here == 'Y') {
                        do_warp(&map_id, &px, &py, &pdir, MAP_VELD, 'Z', 0);
                        door_lock = 20;
                        seq_lines = TALK_FOREST_LEAVE;
                        seq_len = TALK_LEN(TALK_FOREST_LEAVE);
                        seq_beat = 0;
                    }
                    else if(map_id == MAP_FOREST && here == 'O') {
                        do_warp(&map_id, &px, &py, &pdir, MAP_GROVE, 'O', 1);
                        door_lock = 20;
                        seq_lines = TALK_GROVE_ENTER;
                        seq_len = TALK_LEN(TALK_GROVE_ENTER);
                        seq_beat = 0;
                    }
                    else if(map_id == MAP_GROVE && here == 'O') {
                        do_warp(&map_id, &px, &py, &pdir, MAP_FOREST, 'O', 0);
                        door_lock = 20;
                        seq_lines = TALK_GROVE_LEAVE;
                        seq_len = TALK_LEN(TALK_GROVE_LEAVE);
                        seq_beat = 0;
                    }
                }
            }

            if(a_now && !prev_a) {
                if(seq_lines) {
                    /* Advance to the next beat; close the box after
                       the last one. */
                    seq_beat++;
                    if(seq_beat >= seq_len) {
                        seq_lines = 0;
                        seq_len = 0;
                        seq_beat = 0;
                    }
                }
                else if(map_id == MAP_HOUSE) {
                    /* interact(): state.lua's MAP_HOUSE branch,
                       verbatim -- U always shows TALK.bed; B shows
                       TALK.father the first time and TALK.fatherAfter
                       once the shelf is looted; S grants Quillpup
                       (tracked as got_shelf, no party system exists
                       yet to hold it) the first time and shows
                       TALK.shelfEmpty after; C grants a bandage the
                       first time and shows TALK.crateEmpty after.
                       state.lua's other map branches (VELD/FOREST/
                       GROVE: soldiers, Cathleen, Shinigami) aren't
                       ported yet -- those need the battle system
                       first, so interacting elsewhere does nothing
                       this step. */
                    char mark = closest_mark(px, py);

                    switch(mark) {
                        case 'U':
                            seq_lines = TALK_BED;
                            seq_len = TALK_LEN(TALK_BED);
                            break;
                        case 'B':
                            if(got_shelf) {
                                seq_lines = TALK_FATHER_AFTER;
                                seq_len = TALK_LEN(TALK_FATHER_AFTER);
                            }
                            else {
                                seq_lines = TALK_FATHER;
                                seq_len = TALK_LEN(TALK_FATHER);
                            }
                            break;
                        case 'S':
                            if(!got_shelf) {
                                got_shelf = 1;
                                seq_lines = TALK_SHELF;
                                seq_len = TALK_LEN(TALK_SHELF);
                            }
                            else {
                                seq_lines = TALK_SHELF_EMPTY;
                                seq_len = TALK_LEN(TALK_SHELF_EMPTY);
                            }
                            break;
                        case 'C':
                            if(!looted_crate) {
                                looted_crate = 1;
                                bag.bandage++;
                                seq_lines = TALK_CRATE;
                                seq_len = TALK_LEN(TALK_CRATE);
                            }
                            else {
                                seq_lines = TALK_CRATE_EMPTY;
                                seq_len = TALK_LEN(TALK_CRATE_EMPTY);
                            }
                            break;
                        default:
                            break;
                    }
                    seq_beat = 0;
                }
            }

            /* Menu open, only from plain world state (state.lua only
               reaches selectPressed()/startPressed() outside TALK/
               BATTLE/etc, which here just means no dialogue active). */
            if(!seq_lines) {
                if(y_now && !prev_y)
                    menu_mode = 1;
                else if(start_now && !prev_start)
                    menu_mode = 2;
            }
        }

        /* Draw every frame, unconditionally, into the buffer that was
           just hidden by the flip above. See the fb_flip comment for
           why this has to be unconditional now, unlike the earlier
           dirty-check versions. */
        if(state == 0) {
            draw_press_start();
        }
        else {
            compute_camera(map_id, px, py, &cam_x, &cam_y);
            draw_map(map_id, cam_x, cam_y);
            draw_props(map_id, cam_x, cam_y);
            draw_player(px - cam_x, py - cam_y, pdir);
            draw_hud(got_shelf, looted_crate, bag.bandage);
            if(seq_lines)
                draw_dialogue_box(seq_lines[seq_beat]);
            if(menu_mode == 1)
                draw_bag_menu(&bag);
            else if(menu_mode == 2)
                draw_party_menu(got_shelf);
        }

        prev_start = start_now;
        prev_b = b_now;
        prev_y = y_now;
        prev_a = a_now;
    }
}
