/*
 * CryMon - Dreamcast port, step 4: fully wire up the starting room --
 * entities (player + furniture), movement/interact controls, the real
 * multi-beat dialogue for each interactable, the state it gates
 * (getting Quillpup off the shelf, looting the crate), and read-only
 * bag/party menu screens. Leaving the room via the door is still
 * deferred: there's no second map built yet in this port, so the door
 * stays inert regardless of state, unlike the reference where an
 * unlocked door warps to MAP_VELD.
 *
 * Bare-metal, no KallistiOS/BIOS calls. Video setup, vblank sync, and
 * the Maple controller driver are unchanged from step 1 (see that
 * commit / hello-world-dreamcast/src/hello.c for the full derivation
 * notes against KallistiOS's real source).
 *
 * Room layout, tile colors, solid/walkable tiles, prop positions and
 * sizes, player movement speed, and the interactable dialogue/state
 * are all taken from the reference implementation (xenodorian/CryMon):
 *   - love/game/src/data.lua: data.HOUSE (tile grid), data.isSolidTile
 *     (SOLID_SET), data.spawnOf (tile-center world coords), data.TALK
 *     (dialogue text, ported verbatim below except upper-cased and
 *     stripped of punctuation our font can't render), data.START_BAG
 *     / data.START_MARKS (starting bag/marks -- see the Bag struct
 *     below), data.mintMonster (Quillpup's fixed lv3/34hp, see
 *     QUILLPUP_LV/QUILLPUP_MAX_HP below).
 *   - love/game/src/draw.lua: paintTile (tile colors). draw.actor's
 *     colored-silhouette fallback is no longer used for the player --
 *     see sprites.h below.
 *   - love/game/src/render.lua: drawWorld (prop positions used only
 *     to place each prop at its mark's tile center; the sizes
 *     themselves now come from the real art, see sprites.h), the
 *     movement code (speed = 110px/sec at the original's 32px tile
 *     size), and drawBag()/drawParty() (see draw_bag_menu/
 *     draw_party_menu below -- ported as read-only text-row lists,
 *     no item icons, no item-use, no lead-switching, since nothing in
 *     this room's scope needs them yet).
 *   - love/game/src/state.lua: interact()'s MAP_HOUSE branch (the
 *     bed/father/shelf/crate logic and state flags below match it
 *     line for line), sayn() (one dialogue beat shown per A-press,
 *     movement frozen while a sequence is active -- state.lua's
 *     MODE.TALK), and the BAG/PARTY mode update (open/close only, no
 *     cursor logic -- matches the reference, which also only handles
 *     open/close for these two modes).
 * No battle system is ported -- Quillpup is tracked as a bare
 * got_shelf flag plus fixed display stats, not a real party member
 * with HP that can change. The bed's "full heal" is dialogue-only for
 * the same reason: no HP/SP system exists yet to heal.
 *
 * Sprites: sprites.h is generated by tools/gen_sprites.py from
 * xenodorian/CryMon's public/sprites/max/{down,up,left,right}-1.png
 * (max is the protagonist, per data.lua's dialogue lines -- e.g. the
 * bed/shelf/crate TALK entries this room's interact lines are drawn
 * from all use speaker = "max"; mason is a separate rival NPC met
 * later, per data.TALK.masonFight, not used here) and
 * public/sprites/props/{bed-father,bed-empty,shelf,
 * crate}.png -- the reference game's real pixel art, not placeholder
 * art. The bed-father prop art depicts the room's unnamed sick
 * father (data.TALK.father), distinct from both max and mason.
 */

#include <stdint.h>

typedef unsigned char  u8;
typedef unsigned short u16;
typedef unsigned int   u32;

#include "sprites.h"

#define PVR_BASE 0xa05f8000u
#define PVR(reg) (*(volatile u32 *)(PVR_BASE + (reg)))

#define PVR_BORDER_COLOR     0x040
#define PVR_FB_CFG_1         0x044
#define PVR_FB_CFG_2         0x048
#define PVR_RENDER_MODULO    0x04c
#define PVR_FB_ADDR          0x050
#define PVR_FB_SIZE          0x05c
#define PVR_VPOS_IRQ         0x0cc
#define PVR_IL_CFG           0x0d0
#define PVR_BORDER_X         0x0d4
#define PVR_SCAN_CLK         0x0d8
#define PVR_BORDER_Y         0x0dc
#define PVR_VIDEO_CFG        0x0e8
#define PVR_BITMAP_X         0x0ec
#define PVR_BITMAP_Y         0x0f0
#define PVR_SYNC_STATUS      0x10c  /* bits 0-8: nonzero while in vblank */

#define SCREEN_W 320
#define SCREEN_H 240

/* Double buffering, pipelined: each iteration flips to show whatever
   was drawn into the back buffer *last* iteration, then draws the
   next frame into the buffer that just became hidden. This is the
   order a KallistiOS/Dreamcast homebrew community reference (a
   DCEmulation forum thread on KOS double buffering) describes as
   correct: wait_vblank() -> flip the already-drawn buffer into view
   -> only then draw the next frame. The single-buffer version tried
   before this made tearing worse, not better, since every redraw
   wrote directly into whatever the display was actively scanning;
   double buffering keeps drawing entirely off-screen, so only a
   correctly-timed flip is needed to avoid tearing.

   This requires drawing every frame unconditionally, not just when
   something changed: alternating buffers while only sometimes
   redrawing would show one buffer's fresh content and then the
   *other* buffer's stale content every other frame once movement
   stops, which is its own visible glitch. Redrawing every frame is
   safe here specifically because it only ever touches the hidden
   buffer -- it was only unsafe in the single-buffer version. */
#define FB_OFFSET0 0x000000u
#define FB_OFFSET1 0x040000u

static u32 fb_back_offset = FB_OFFSET1;
static volatile u16 *draw_fb = (volatile u16 *)(0xa5000000u + FB_OFFSET1);

static void fb_flip(void) {
    PVR(PVR_FB_ADDR) = fb_back_offset;
    fb_back_offset = (fb_back_offset == FB_OFFSET0) ? FB_OFFSET1 : FB_OFFSET0;
    draw_fb = (volatile u16 *)(0xa5000000u + fb_back_offset);
}

/* DM_320x240_NTSC timing parameters, from KallistiOS's vid_builtin table */
#define SCANLINES 262
#define CLOCKS    857
#define BITMAPX   164
#define BITMAPY   24
#define SCANINT1  21
#define SCANINT2  260
#define BORDERX1  141
#define BORDERX2  843
#define BORDERY1  24
#define BORDERY2  263

static void video_init(void) {
    PVR(PVR_VIDEO_CFG) = PVR(PVR_VIDEO_CFG) | 0x8u;
    PVR(PVR_FB_CFG_1)  = PVR(PVR_FB_CFG_1) & ~1u;

    PVR(PVR_BORDER_COLOR) = 0;

    PVR(PVR_FB_CFG_1) = (1u << 2);
    PVR(PVR_FB_CFG_2) = 1u | (1u << 3);

    PVR(PVR_RENDER_MODULO) = (SCREEN_W * 2) / 8;
    PVR(PVR_FB_ADDR) = 0;

    PVR(PVR_FB_SIZE) = (((SCREEN_W * 2) / 4) - 1)
                      | (1u << 20)
                      | ((SCREEN_H - 1u) << 10);

    PVR(PVR_VPOS_IRQ) = (SCANINT1 << 16) | SCANINT2;
    PVR(PVR_IL_CFG) = 0x100;

    PVR(PVR_BORDER_X) = (BORDERX1 << 16) | BORDERX2;
    PVR(PVR_BORDER_Y) = (BORDERY1 << 16) | BORDERY2;
    PVR(PVR_SCAN_CLK) = (SCANLINES << 16) | CLOCKS;

    PVR(PVR_VIDEO_CFG) = PVR(PVR_VIDEO_CFG) | 0x100u;

    PVR(PVR_BITMAP_X) = BITMAPX;
    PVR(PVR_BITMAP_Y) = (BITMAPY << 16) | BITMAPY;

    *(volatile u32 *)0xa0702c00 =
        (*(volatile u32 *)0xa0702c00 & 0xfffffcffu) | (3u << 8);

    PVR(PVR_VIDEO_CFG) = PVR(PVR_VIDEO_CFG) & ~0x8u;
    PVR(PVR_FB_CFG_1)  = PVR(PVR_FB_CFG_1) | 1u;
}

/* Checked against KallistiOS's own vid_waitvbl() (hardware/video.c):
   wait for vblank to start, then wait for it to end, so each call
   corresponds to exactly one fresh frame. */
static void wait_vblank(void) {
    while(!(PVR(PVR_SYNC_STATUS) & 0x01ffu))
        ;
    while(PVR(PVR_SYNC_STATUS) & 0x01ffu)
        ;
}

static void vram_clear(void) {
    u32 i;
    for(i = 0; i < (u32)SCREEN_W * SCREEN_H; i++)
        draw_fb[i] = 0x0000;
}

static void put_pixel(int x, int y, u16 color) {
    if(x < 0 || x >= SCREEN_W || y < 0 || y >= SCREEN_H)
        return;
    draw_fb[y * SCREEN_W + x] = color;
}

static void fill_rect(int x, int y, int w, int h, u16 color) {
    int px, py;
    for(py = y; py < y + h; py++)
        for(px = x; px < x + w; px++)
            put_pixel(px, py, color);
}

static u16 rgb565(u8 r, u8 g, u8 b) {
    return (u16)(((r >> 3) << 11) | ((g >> 2) << 5) | (b >> 3));
}

/* Blits a w x h RGB565 sprite (see sprites.h) with its top-left
   corner at (x, y), skipping any pixel equal to SPRITE_KEY
   (color-keyed transparency -- the sprite has no separate alpha
   channel once baked into the array). */
static void blit_sprite(const u16 *px, int w, int h, int x, int y) {
    int sx, sy;
    for(sy = 0; sy < h; sy++) {
        for(sx = 0; sx < w; sx++) {
            u16 c = px[sy * w + sx];
            if(c != SPRITE_KEY)
                put_pixel(x + sx, y + sy, c);
        }
    }
}

/* ----------------------------------------------------------------------
 * Font: 8x8, 1bpp glyphs, A-Z + space. Bit 7 = leftmost pixel of each
 * row. Enough to render the interact-dialogue lines and the title
 * screen; text is upper-cased and punctuation-free by construction.
 * ---------------------------------------------------------------------- */
static const uint8_t font_AZ[26][8] = {
    /* A */ { 0b00111100, 0b01000010, 0b10000001, 0b10000001,
              0b11111111, 0b10000001, 0b10000001, 0b00000000 },
    /* B */ { 0b11111100, 0b10000010, 0b10000010, 0b11111100,
              0b10000010, 0b10000010, 0b11111100, 0b00000000 },
    /* C */ { 0b01111110, 0b10000000, 0b10000000, 0b10000000,
              0b10000000, 0b10000000, 0b01111110, 0b00000000 },
    /* D */ { 0b11111100, 0b10000010, 0b10000001, 0b10000001,
              0b10000001, 0b10000010, 0b11111100, 0b00000000 },
    /* E */ { 0b11111111, 0b10000000, 0b10000000, 0b11111100,
              0b10000000, 0b10000000, 0b11111111, 0b00000000 },
    /* F */ { 0b11111111, 0b10000000, 0b10000000, 0b11111100,
              0b10000000, 0b10000000, 0b10000000, 0b00000000 },
    /* G */ { 0b01111110, 0b10000000, 0b10000000, 0b10001111,
              0b10000001, 0b10000001, 0b01111110, 0b00000000 },
    /* H */ { 0b10000001, 0b10000001, 0b10000001, 0b11111111,
              0b10000001, 0b10000001, 0b10000001, 0b00000000 },
    /* I */ { 0b11111111, 0b00011000, 0b00011000, 0b00011000,
              0b00011000, 0b00011000, 0b11111111, 0b00000000 },
    /* J */ { 0b00000111, 0b00000010, 0b00000010, 0b00000010,
              0b10000010, 0b10000010, 0b01111100, 0b00000000 },
    /* K */ { 0b10000010, 0b10000100, 0b10001000, 0b11110000,
              0b10001000, 0b10000100, 0b10000010, 0b00000000 },
    /* L */ { 0b10000000, 0b10000000, 0b10000000, 0b10000000,
              0b10000000, 0b10000000, 0b11111111, 0b00000000 },
    /* M */ { 0b10000001, 0b11000011, 0b10100101, 0b10011001,
              0b10000001, 0b10000001, 0b10000001, 0b00000000 },
    /* N */ { 0b10000001, 0b11000001, 0b10100001, 0b10010001,
              0b10001001, 0b10000101, 0b10000011, 0b00000000 },
    /* O */ { 0b01111110, 0b10000001, 0b10000001, 0b10000001,
              0b10000001, 0b10000001, 0b01111110, 0b00000000 },
    /* P */ { 0b11111100, 0b10000010, 0b10000010, 0b11111100,
              0b10000000, 0b10000000, 0b10000000, 0b00000000 },
    /* Q */ { 0b01111110, 0b10000001, 0b10000001, 0b10000001,
              0b10010101, 0b10001001, 0b01110110, 0b00000000 },
    /* R */ { 0b11111110, 0b10000001, 0b10000001, 0b11111110,
              0b10010000, 0b10001000, 0b10000100, 0b00000000 },
    /* S */ { 0b01111110, 0b10000000, 0b10000000, 0b01111100,
              0b00000010, 0b00000010, 0b11111100, 0b00000000 },
    /* T */ { 0b11111111, 0b00011000, 0b00011000, 0b00011000,
              0b00011000, 0b00011000, 0b00011000, 0b00000000 },
    /* U */ { 0b10000001, 0b10000001, 0b10000001, 0b10000001,
              0b10000001, 0b10000001, 0b01111110, 0b00000000 },
    /* V */ { 0b10000001, 0b10000001, 0b10000001, 0b01000010,
              0b01000010, 0b00100100, 0b00011000, 0b00000000 },
    /* W */ { 0b10000001, 0b10000001, 0b10000001, 0b10100101,
              0b10100101, 0b11011011, 0b10000001, 0b00000000 },
    /* X */ { 0b10000001, 0b01000010, 0b00100100, 0b00011000,
              0b00100100, 0b01000010, 0b10000001, 0b00000000 },
    /* Y */ { 0b10000001, 0b01000010, 0b00100100, 0b00011000,
              0b00011000, 0b00011000, 0b00011000, 0b00000000 },
    /* Z */ { 0b11111111, 0b00000010, 0b00000100, 0b00001000,
              0b00010000, 0b00100000, 0b11111111, 0b00000000 },
};

/* Digits 0-9, same style/size as font_AZ. Needed for the room's HUD
   (Quillpup's level, the bandage count) -- nothing in the dialogue
   text itself uses digits. */
static const uint8_t font_09[10][8] = {
    /* 0 */ { 0b00111100, 0b01100110, 0b01101110, 0b01110110,
              0b01100110, 0b01100110, 0b00111100, 0b00000000 },
    /* 1 */ { 0b00011000, 0b00111000, 0b00011000, 0b00011000,
              0b00011000, 0b00011000, 0b01111110, 0b00000000 },
    /* 2 */ { 0b00111100, 0b01100110, 0b00000110, 0b00001100,
              0b00011000, 0b00110000, 0b01111110, 0b00000000 },
    /* 3 */ { 0b00111100, 0b01100110, 0b00000110, 0b00011100,
              0b00000110, 0b01100110, 0b00111100, 0b00000000 },
    /* 4 */ { 0b00001100, 0b00011100, 0b00101100, 0b01001100,
              0b01111110, 0b00001100, 0b00001100, 0b00000000 },
    /* 5 */ { 0b01111110, 0b01100000, 0b01111100, 0b00000110,
              0b00000110, 0b01100110, 0b00111100, 0b00000000 },
    /* 6 */ { 0b00011100, 0b00110000, 0b01100000, 0b01111100,
              0b01100110, 0b01100110, 0b00111100, 0b00000000 },
    /* 7 */ { 0b01111110, 0b00000110, 0b00001100, 0b00011000,
              0b00110000, 0b00110000, 0b00110000, 0b00000000 },
    /* 8 */ { 0b00111100, 0b01100110, 0b01100110, 0b00111100,
              0b01100110, 0b01100110, 0b00111100, 0b00000000 },
    /* 9 */ { 0b00111100, 0b01100110, 0b01100110, 0b00111110,
              0b00000110, 0b00001100, 0b00111000, 0b00000000 },
};

static void draw_glyph(int ox, int oy, const uint8_t bitmap[8], u16 color, int scale) {
    int row, col, sx, sy;

    for(row = 0; row < 8; row++) {
        uint8_t bits = bitmap[row];

        for(col = 0; col < 8; col++) {
            if(!(bits & (0x80 >> col)))
                continue;

            for(sy = 0; sy < scale; sy++)
                for(sx = 0; sx < scale; sx++)
                    put_pixel(ox + col * scale + sx, oy + row * scale + sy, color);
        }
    }
}

static void draw_text_s(const char *s, int x, int y, u16 color, int scale) {
    int cx = x;
    int px = 8 * scale;
    for(; *s; s++) {
        if(*s >= 'A' && *s <= 'Z')
            draw_glyph(cx, y, font_AZ[*s - 'A'], color, scale);
        else if(*s >= '0' && *s <= '9')
            draw_glyph(cx, y, font_09[*s - '0'], color, scale);
        cx += px;
    }
}

static int text_width_s(const char *s, int scale) {
    int n = 0;
    for(; *s; s++) n++;
    return n * 8 * scale;
}

static void draw_text_center_s(const char *s, int cx, int y, u16 color, int scale) {
    draw_text_s(s, cx - text_width_s(s, scale) / 2, y, color, scale);
}

static int word_len(const char *s) {
    int n = 0;
    while(s[n] && s[n] != ' ')
        n++;
    return n;
}

/* Word-wraps s (space-separated, uppercase-and-punctuation-free like
   every TALK string below) into lines of at most max_chars columns,
   greedily packing words, and draws each line left-aligned at x
   starting at y with line_h pixels between line tops. Used for the
   dialogue box, whose longest ported line (data.TALK.shelf's second
   beat) wraps to exactly 3 lines -- the box is sized for that. */
#define WRAP_BUF_MAX 40
static void draw_wrapped(const char *s, int x, int y, u16 color, int scale,
                          int max_chars, int line_h) {
    char buf[WRAP_BUF_MAX + 1];
    int buf_len = 0;
    int line = 0;
    const char *p = s;

    for(;;) {
        int wlen = word_len(p);
        int need = wlen + (buf_len > 0 ? 1 : 0);

        if(buf_len > 0 && buf_len + need > max_chars) {
            buf[buf_len] = 0;
            draw_text_s(buf, x, y + line * line_h, color, scale);
            line++;
            buf_len = 0;
        }

        if(buf_len > 0)
            buf[buf_len++] = ' ';
        {
            int i;
            for(i = 0; i < wlen && buf_len < WRAP_BUF_MAX; i++)
                buf[buf_len++] = p[i];
        }

        p += wlen;
        if(*p != ' ')
            break;
        p++;
    }

    buf[buf_len] = 0;
    draw_text_s(buf, x, y + line * line_h, color, scale);
}

/* ----------------------------------------------------------------------
 * Tiny manual string building for the HUD/bag/party rows below (no
 * libc here -- nostdlib/ffreestanding). s_cat/s_cat_uint append to a
 * caller-owned buffer and return the new length; callers chain them
 * to build one row's text before a single draw_text_s call.
 * ---------------------------------------------------------------------- */
static int s_cat(char *dst, int len, const char *src) {
    while(*src)
        dst[len++] = *src++;
    return len;
}

static int s_cat_uint(char *dst, int len, int v) {
    char tmp[6];
    int n = 0;
    if(v == 0) {
        dst[len++] = '0';
        return len;
    }
    while(v > 0 && n < 6) {
        tmp[n++] = (char)('0' + (v % 10));
        v /= 10;
    }
    while(n > 0)
        dst[len++] = tmp[--n];
    return len;
}

#define TITLE_SCALE 3
#define DIALOGUE_SCALE 1

static void draw_press_start(void) {
    vram_clear();
    draw_text_center_s("PRESS START", SCREEN_W / 2,
                        SCREEN_H / 2 - 4 * TITLE_SCALE, 0xFFFF, TITLE_SCALE);
}

/* ----------------------------------------------------------------------
 * Minimal Maple bus controller driver (port A / unit 0 only). Same
 * derivation as hello-world-dreamcast/src/hello.c -- see that file for
 * the full explanation of the register layout and packet format,
 * checked against KallistiOS's own Maple driver source.
 * ---------------------------------------------------------------------- */
#define MAPLE_BASE      0xa05f6c00u
#define MAPLE_DMA_ADDR  (*(volatile u32 *)(MAPLE_BASE + 0x04))
#define MAPLE_DMA_TSEL  (*(volatile u32 *)(MAPLE_BASE + 0x10))
#define MAPLE_ENABLE    (*(volatile u32 *)(MAPLE_BASE + 0x14))
#define MAPLE_STATE     (*(volatile u32 *)(MAPLE_BASE + 0x18))
#define MAPLE_SPEED     (*(volatile u32 *)(MAPLE_BASE + 0x80))
#define MAPLE_DMA_PROT  (*(volatile u32 *)(MAPLE_BASE + 0x8c))

#define MAPLE_COMMAND_GETCOND   9
#define MAPLE_RESPONSE_DATATRF  8
#define MAPLE_FUNC_CONTROLLER   0x01000000u

#define CONT_C            (1u << 0)
#define CONT_B            (1u << 1)
#define CONT_A            (1u << 2)
#define CONT_START        (1u << 3)
#define CONT_DPAD_UP      (1u << 4)
#define CONT_DPAD_DOWN    (1u << 5)
#define CONT_DPAD_LEFT    (1u << 6)
#define CONT_DPAD_RIGHT   (1u << 7)
#define CONT_Z            (1u << 8)
#define CONT_Y            (1u << 9)
#define CONT_X            (1u << 10)

static u32 maple_cmd_buf[8]  __attribute__((aligned(32)));
static u32 maple_resp_buf[64] __attribute__((aligned(32)));

#define P2(p)   ((volatile u32 *)(((u32)(p)) | 0x20000000u))
#define PHYS(p) (((u32)(p)) & 0x1fffffffu)

static void maple_init(void) {
    MAPLE_DMA_PROT = 0x6155404fu;
    MAPLE_DMA_TSEL = 0;
    MAPLE_SPEED = 0x0000u | (50000u << 16);
    MAPLE_ENABLE = 1;
}

static u16 maple_poll_buttons(void) {
    volatile u32 *cmd  = P2(maple_cmd_buf);
    volatile u32 *resp = P2(maple_resp_buf);
    u32 timeout;

    cmd[0] = 1u | (0u << 16) | 0x80000000u;
    cmd[1] = PHYS(maple_resp_buf);
    cmd[2] = MAPLE_COMMAND_GETCOND | (0x20u << 8) | (0u << 16) | (1u << 24);
    cmd[3] = MAPLE_FUNC_CONTROLLER;

    MAPLE_DMA_ADDR = PHYS(maple_cmd_buf);
    MAPLE_STATE = 1;

    for(timeout = 0; timeout < 2000000u; timeout++) {
        if(MAPLE_STATE == 0)
            break;
    }
    if(MAPLE_STATE != 0)
        return 0xffff;

    if((resp[0] & 0xffu) != MAPLE_RESPONSE_DATATRF)
        return 0xffff;
    if(resp[1] != MAPLE_FUNC_CONTROLLER)
        return 0xffff;

    return (u16)(resp[2] & 0xffffu);
}

static int pressed(u16 raw, u16 mask) {
    return (raw & mask) == 0;
}

/* ----------------------------------------------------------------------
 * The starting room ("HOUSE"), verbatim from CryMon's
 * love/game/src/data.lua (data.HOUSE), data.isSolidTile (SOLID_SET),
 * and love/game/src/draw.lua (paintTile). 14 columns x 11 rows, 32px
 * tiles in the original; drawn here at 20px tiles (280x220) so the
 * whole room fits centered on the Dreamcast's 320x240 screen -- this
 * step doesn't need camera scrolling since nothing leaves the room.
 * ---------------------------------------------------------------------- */
#define ROOM_TILE   20
#define ROOM_COLS   14
#define ROOM_ROWS   11
#define ROOM_OX     ((SCREEN_W - ROOM_COLS * ROOM_TILE) / 2)
#define ROOM_OY     ((SCREEN_H - ROOM_ROWS * ROOM_TILE) / 2)

static const char *const house_room[ROOM_ROWS] = {
    "HHHHHHHHHHHHHH",
    "HFFFFFFFFFFFFH",
    "HFFFFFFFFFFFFH",
    "HFFFFFFFFFFFFH",
    "HFBFFFFSFFFCFH",
    "HFFFFFFFFFFFFH",
    "HUFFFFFFFFFFFH",
    "HFFFFPFFFFFFFH",
    "HFFFFFFFFFFFFH",
    "HFFFFFFFFFFFFH",
    "HHHHHHDHHHHHHH",
};

/* data.lua's SOLID_SET restricted to the characters that actually
   appear in HOUSE: H (wall), B (father's bed), C (crate), U (empty
   bed) are solid; F, P, D, S are walkable (yes, the shelf tile itself
   is walkable in the reference game -- SOLID_SET has no 'S' in it). */
static int tile_is_solid(char ch) {
    return ch == 'H' || ch == 'B' || ch == 'C' || ch == 'U';
}

static char tile_at(int col, int row) {
    if(col < 0 || col >= ROOM_COLS || row < 0 || row >= ROOM_ROWS)
        return 'H';
    return house_room[row][col];
}

static void find_mark(char mark, int *out_col, int *out_row) {
    int row, col;
    for(row = 0; row < ROOM_ROWS; row++) {
        for(col = 0; col < ROOM_COLS; col++) {
            if(house_room[row][col] == mark) {
                *out_col = col;
                *out_row = row;
                return;
            }
        }
    }
    *out_col = 2;
    *out_row = 2;
}

static void draw_room_tile(char ch, int dx, int dy) {
    int t = ROOM_TILE;

    switch(ch) {
        case 'H':
            fill_rect(dx, dy, t, t, rgb565(42, 30, 22));
            return;
        case 'D':
            fill_rect(dx, dy, t, t, rgb565(26, 18, 12));
            return;
        case 'F':
        case 'P':
        case 'B':
        case 'U':
        case 'C':
        case 'S':
        default:
            fill_rect(dx, dy, t, t, rgb565(106, 82, 56));
            return;
    }
}

static void draw_house_background(void) {
    int row, col;

    /* The room (280x220) doesn't cover the full 320x240 screen, so
       the border margin needs clearing or it would show whatever was
       drawn there previously (e.g. the title screen text). */
    vram_clear();

    for(row = 0; row < ROOM_ROWS; row++)
        for(col = 0; col < ROOM_COLS; col++)
            draw_room_tile(house_room[row][col],
                            ROOM_OX + col * ROOM_TILE, ROOM_OY + row * ROOM_TILE);
}

static void mark_center(char mark, int *out_x, int *out_y) {
    int col, row;
    find_mark(mark, &col, &row);
    *out_x = ROOM_OX + col * ROOM_TILE + ROOM_TILE / 2;
    *out_y = ROOM_OY + row * ROOM_TILE + ROOM_TILE / 2;
}

/* Props are center-anchored on their mark's tile center, matching the
   flat-rect placeholders this replaces. Sizes come from sprites.h
   (the real art's own dimensions, downscaled by gen_sprites.py --
   not the original 32px-tile-space sizes from render.lua, which
   didn't match the actual art's proportions anyway). */
static void draw_prop(char mark, const u16 *px, int w, int h) {
    int cx, cy;
    mark_center(mark, &cx, &cy);
    blit_sprite(px, w, h, cx - w / 2, cy - h / 2);
}

static void draw_props(void) {
    draw_prop('B', prop_bed_father, PROP_BED_FATHER_W, PROP_BED_FATHER_H);
    draw_prop('U', prop_bed_empty, PROP_BED_EMPTY_W, PROP_BED_EMPTY_H);
    draw_prop('S', prop_shelf, PROP_SHELF_W, PROP_SHELF_H);
    draw_prop('C', prop_crate, PROP_CRATE_W, PROP_CRATE_H);
}

/* Player sprite, bottom-center anchored at (cx, cy) same as the
   silhouette this replaces (draw.lua's draw.actor() used the same
   anchor). dir matches the sprite arrays below: 0=down,1=up,2=left,
   3=right. */
static void draw_player(int cx, int cy, int dir) {
    static const u16 *const frames[4] = {
        max_down, max_up, max_left, max_right
    };
    int x = cx - MAX_SPRITE_W / 2, y = cy - MAX_SPRITE_H;
    blit_sprite(frames[dir], MAX_SPRITE_W, MAX_SPRITE_H, x, y);
}

/* ----------------------------------------------------------------------
 * Interact dialogue: full multi-beat sequences from data.TALK.father /
 * fatherAfter / bed / shelf / shelfEmpty / crate / crateEmpty
 * (love/game/src/data.lua), verbatim except upper-cased and stripped
 * of punctuation our A-Z/0-9-only font can't render. Each sequence is
 * shown one beat per A-press (matching sayn()'s one-beat-per-advance
 * in the reference), word-wrapped into the dialogue box.
 * ---------------------------------------------------------------------- */
static const char *const TALK_FATHER[] = {
    "THERES A WAR CRYTOWN IS ALREADY BLEEDING",
    "YOURE TOO SICK TO DEFEND IT FROM THE SOLDIERS I KNOW THAT",
    "SO IM STEALING YOUR CRYMON",
    "FATHER DOES NOT WAKE THE CAPTURE CRYSTAL IS STILL ON THE SHELF",
};
static const char *const TALK_FATHER_AFTER[] = {
    "I ALREADY TOOK QUILLPUP SLEEP ILL DO THE FIGHTING",
    "HIS BREATH IS THIN HE DOES NOT ANSWER",
};
static const char *const TALK_BED[] = {
    "JUST UNTIL THEY BREATHE AGAIN",
    "MAXS EMPTY BED THE CRYMON SLEEP CUTS CLOSE SPECIALS RETURN",
};
static const char *const TALK_SHELF[] = {
    "THIS IS IT FATHERS CRYSTAL QUILLPUP IS INSIDE",
    "THE CRYSTAL BREAKS WARM IN HER HANDS QUILLPUP SHAKES OUT ONTO THE FLOORBOARDS",
    "YOURE COMING CRYTOWN DOESNT GET TO FALL",
};
static const char *const TALK_SHELF_EMPTY[] = {
    "DUST THE CRYSTAL IS ALREADY OPEN",
};
static const char *const TALK_CRATE[] = {
    "A WRAP HE WONT MISS IT",
    "A LINEN WRAP UNDER THE LID YOU TAKE IT",
};
static const char *const TALK_CRATE_EMPTY[] = {
    "SPLINTERS AND A MOTH EMPTY",
};

#define TALK_LEN(arr) (int)(sizeof(arr) / sizeof((arr)[0]))

#define DIALOGUE_MAX_CHARS 37
#define DIALOGUE_LINE_H    9

static void draw_dialogue_box(const char *line) {
    fill_rect(4, SCREEN_H - 44, SCREEN_W - 8, 40, rgb565(18, 17, 14));
    fill_rect(4, SCREEN_H - 44, SCREEN_W - 8, 2, rgb565(197, 206, 198));
    fill_rect(4, SCREEN_H - 6, SCREEN_W - 8, 2, rgb565(197, 206, 198));
    draw_wrapped(line, 12, SCREEN_H - 38, rgb565(232, 228, 216), DIALOGUE_SCALE,
                 DIALOGUE_MAX_CHARS, DIALOGUE_LINE_H);
}

/* Small HUD overlaid on the room's top wall row, showing what the
   room has granted so far -- there's no inventory/party menu in this
   port yet, so this is the only on-screen confirmation that
   interacting actually changed state. */
static void draw_hud(int got_shelf, int looted_crate, int bag_bandage) {
    int y = ROOM_OY + 2;

    if(got_shelf) {
        const char *label = "QUILLPUP LV";
        draw_text_s(label, ROOM_OX + 4, y, 0xFFFF, DIALOGUE_SCALE);
        draw_glyph(ROOM_OX + 4 + text_width_s(label, DIALOGUE_SCALE), y,
                   font_09[3], 0xFFFF, DIALOGUE_SCALE);
        y += DIALOGUE_LINE_H;
    }
    if(looted_crate) {
        const char *label = "BANDAGE X";
        draw_text_s(label, ROOM_OX + 4, y, 0xFFFF, DIALOGUE_SCALE);
        draw_glyph(ROOM_OX + 4 + text_width_s(label, DIALOGUE_SCALE), y,
                   font_09[bag_bandage % 10], 0xFFFF, DIALOGUE_SCALE);
    }
}

/* ----------------------------------------------------------------------
 * Bag and party menus, ported from render.lua's drawBag()/drawParty().
 * Both are read-only overlays here (no item use, no lead-switching --
 * nothing in this room's scope needs either yet): open with Y (bag) or
 * START (party), close with B. data.lua's START_BAG gives the room's
 * starting counts (salve 2, bandage 2, bitterroot 1, dust 1, gem 0)
 * and START_MARKS (16); the bandage count is the only one this room
 * ever changes (the crate). Item icons (render.lua's "item-<id>"
 * sprites) aren't ported -- text rows only, like the rest of this
 * step's UI.
 * ---------------------------------------------------------------------- */
typedef struct {
    int salve, bandage, bitterroot, dust, gem;
} Bag;

#define MARKS_START 16

#define MENU_X 20
#define MENU_Y 20
#define MENU_W (SCREEN_W - 2 * MENU_X)
#define MENU_H (SCREEN_H - 2 * MENU_Y)
#define MENU_SCALE 1
#define MENU_ROW_H 16

static void draw_menu_frame(const char *title) {
    fill_rect(MENU_X, MENU_Y, MENU_W, MENU_H, rgb565(18, 17, 14));
    fill_rect(MENU_X, MENU_Y, MENU_W, 2, rgb565(197, 206, 198));
    fill_rect(MENU_X, MENU_Y + MENU_H - 2, MENU_W, 2, rgb565(197, 206, 198));
    draw_text_s(title, MENU_X + 8, MENU_Y + 8, rgb565(197, 206, 198), MENU_SCALE);
    draw_text_s("B CLOSE", MENU_X + 8, MENU_Y + MENU_H - 16,
                rgb565(90, 122, 82), MENU_SCALE);
}

static void draw_bag_row(const char *label, int count, int y) {
    char buf[32];
    int n = s_cat(buf, 0, label);
    n = s_cat(buf, n, " X");
    n = s_cat_uint(buf, n, count);
    buf[n] = 0;
    draw_text_s(buf, MENU_X + 8, y, rgb565(232, 228, 216), MENU_SCALE);
}

static void draw_bag_menu(const Bag *bag) {
    int y = MENU_Y + 24;
    char marks_buf[16];
    int n;

    draw_menu_frame("BAG");

    n = s_cat(marks_buf, 0, "MARKS ");
    n = s_cat_uint(marks_buf, n, MARKS_START);
    marks_buf[n] = 0;
    draw_text_s(marks_buf, MENU_X + MENU_W - 8 - text_width_s(marks_buf, MENU_SCALE),
                MENU_Y + 8, rgb565(143, 74, 64), MENU_SCALE);

    draw_bag_row("MOSS SALVE", bag->salve, y);       y += MENU_ROW_H;
    draw_bag_row("LINEN WRAP", bag->bandage, y);     y += MENU_ROW_H;
    draw_bag_row("BITTERROOT", bag->bitterroot, y);  y += MENU_ROW_H;
    draw_bag_row("ASH DUST", bag->dust, y);          y += MENU_ROW_H;
    draw_bag_row("CAPTURE CRYSTAL", bag->gem, y);
}

/* Quillpup's stats at the level this room mints it (mintMonster's
   growth curve: g = 1 + (lv-3)*0.12, so lv 3 gives g == 1 exactly --
   maxHp = floor(34*1 + 0.5) = 34, matching data.lua's quillpup
   species entry). No battle system exists yet to change hp from
   maxHp, so it's shown here as always full. */
#define QUILLPUP_LV     3
#define QUILLPUP_MAX_HP 34

static void draw_party_menu(int got_shelf) {
    int y = MENU_Y + 24;

    draw_menu_frame("CRYMON");

    if(got_shelf) {
        char buf[40];
        int n = s_cat(buf, 0, "> QUILLPUP LV");
        n = s_cat_uint(buf, n, QUILLPUP_LV);
        n = s_cat(buf, n, " HP ");
        n = s_cat_uint(buf, n, QUILLPUP_MAX_HP);
        n = s_cat(buf, n, "/");
        n = s_cat_uint(buf, n, QUILLPUP_MAX_HP);
        buf[n] = 0;
        draw_text_s(buf, MENU_X + 8, y, rgb565(232, 228, 216), MENU_SCALE);
    }
    else {
        draw_text_s("NO CRYMON YET", MENU_X + 8, y, rgb565(138, 134, 120), MENU_SCALE);
    }
}

/* interact() in state.lua: closest of U/B/S/C within a 36px radius
   (36*36=1296) in the original's 32px-tile space; scaled to our 20px
   tiles that's a 22.5px radius (22*22=484). */
static char closest_mark(int px, int py) {
    static const char marks[4] = { 'U', 'B', 'S', 'C' };
    int i;
    int best = 484, best_i = -1;

    for(i = 0; i < 4; i++) {
        int mx, my, dx, dy, d;
        mark_center(marks[i], &mx, &my);
        dx = px - mx;
        dy = py - my;
        d = dx * dx + dy * dy;
        if(d <= best) {
            best = d;
            best_i = i;
        }
    }
    return best_i >= 0 ? marks[best_i] : 0;
}

void main(void) {
    int state = 0; /* 0 = title screen, 1 = starting room */
    int prev_start = 0, prev_a = 0, prev_b = 0, prev_y = 0;
    int px, py, pdir = 0; /* dir: 0=down,1=up,2=left,3=right */
    int col, row;
    u16 raw;
    int start_now, a_now, b_now, y_now;

    /* Room state, matching state.lua's G.gotShelf / G.lootedCrate /
       G.bag (data.START_BAG). No HP/SP system exists yet, so the
       bed's "full heal" (state.lua's fullHeal()) has nothing to do
       here beyond showing its dialogue; no battle/party system
       exists yet either, so Quillpup is tracked only as the
       got_shelf flag plus the HUD/party-menu lines, not as a real
       party member. */
    int got_shelf = 0, looted_crate = 0;
    Bag bag = { 2, 2, 1, 1, 0 }; /* salve, bandage, bitterroot, dust, gem */

    /* 0 = no menu, 1 = bag, 2 = party. Opened from the world with Y /
       START (state.lua's selectPressed()/startPressed() -- there's no
       Select button on a Dreamcast pad, so Y stands in for it), closed
       with B (state.lua's cancelPressed(), which also accepts start
       and select; B alone is enough here since neither Y nor START
       need a second meaning while a menu is open). */
    int menu_mode = 0;

    /* Active dialogue sequence: seq_lines/seq_len name the current
       TALK_* array, seq_beat indexes into it. seq_lines == 0 means no
       dialogue is showing. */
    const char *const *seq_lines = 0;
    int seq_len = 0, seq_beat = 0;

    video_init();
    maple_init();

    find_mark('P', &col, &row);
    px = ROOM_OX + col * ROOM_TILE + ROOM_TILE / 2;
    py = ROOM_OY + row * ROOM_TILE + ROOM_TILE / 2;

    /* Prime both buffers with the title screen before the main loop
       starts flipping, so the first flip doesn't show whatever
       garbage was in VRAM at boot. */
    draw_press_start();
    fb_flip();
    draw_press_start();

    for(;;) {
        wait_vblank();
        fb_flip();

        raw = maple_poll_buttons();
        start_now = pressed(raw, CONT_START);
        a_now     = pressed(raw, CONT_A);
        b_now     = pressed(raw, CONT_B);
        y_now     = pressed(raw, CONT_Y);

        if(state == 0) {
            if(start_now && !prev_start)
                state = 1;
        }
        else if(menu_mode) {
            /* state.lua's MODE.BAG/MODE.PARTY update: only closing is
               handled, matching the reference (no cursor/use/swap
               logic in this port's scope). */
            if((b_now && !prev_b) || (start_now && !prev_start))
                menu_mode = 0;
        }
        else {
            /* Movement is frozen while a dialogue sequence is active,
               matching state.lua's MODE.TALK (movement there is only
               processed in MODE.WALK). */
            if(!seq_lines) {
                int dx = 0, dy = 0;

                if(pressed(raw, CONT_DPAD_LEFT))  { dx = -1; pdir = 2; }
                if(pressed(raw, CONT_DPAD_RIGHT)) { dx = 1;  pdir = 3; }
                if(pressed(raw, CONT_DPAD_UP))    { dy = -1; pdir = 1; }
                if(pressed(raw, CONT_DPAD_DOWN))  { dy = 1;  pdir = 0; }

                if(dx != 0 || dy != 0) {
                    /* Axis-separated movement so the player slides
                       along walls instead of stopping dead on a
                       diagonal. Half the collision box (6px) is
                       checked at the candidate feet position. */
                    int speed = 1; /* px/frame; ~60px/sec at 60fps,
                                       scaled down from the original's
                                       110px/sec at 32px tiles for our
                                       smaller room */
                    int nx = px + dx * speed;
                    int ny = py + dy * speed;

                    if(dx != 0 && !tile_is_solid(tile_at((nx + (dx > 0 ? 6 : -6) - ROOM_OX) / ROOM_TILE,
                                                          (py - ROOM_OY) / ROOM_TILE))) {
                        px = nx;
                    }
                    if(dy != 0 && !tile_is_solid(tile_at((px - ROOM_OX) / ROOM_TILE,
                                                          (ny + (dy > 0 ? 6 : -6) - ROOM_OY) / ROOM_TILE))) {
                        py = ny;
                    }

                    if(px < ROOM_OX + 8) px = ROOM_OX + 8;
                    if(px > ROOM_OX + ROOM_COLS * ROOM_TILE - 8) px = ROOM_OX + ROOM_COLS * ROOM_TILE - 8;
                    if(py < ROOM_OY + 8) py = ROOM_OY + 8;
                    if(py > ROOM_OY + ROOM_ROWS * ROOM_TILE - 4) py = ROOM_OY + ROOM_ROWS * ROOM_TILE - 4;
                }
            }

            if(a_now && !prev_a) {
                if(seq_lines) {
                    /* Advance to the next beat; close the box after
                       the last one. */
                    seq_beat++;
                    if(seq_beat >= seq_len) {
                        seq_lines = 0;
                        seq_len = 0;
                        seq_beat = 0;
                    }
                }
                else {
                    /* interact(): state.lua's MAP_HOUSE branch,
                       verbatim -- U always shows TALK.bed; B shows
                       TALK.father the first time and TALK.fatherAfter
                       once the shelf is looted; S grants Quillpup
                       (tracked as got_shelf, no party system exists
                       yet to hold it) the first time and shows
                       TALK.shelfEmpty after; C grants a bandage the
                       first time and shows TALK.crateEmpty after. */
                    char mark = closest_mark(px, py);

                    switch(mark) {
                        case 'U':
                            seq_lines = TALK_BED;
                            seq_len = TALK_LEN(TALK_BED);
                            break;
                        case 'B':
                            if(got_shelf) {
                                seq_lines = TALK_FATHER_AFTER;
                                seq_len = TALK_LEN(TALK_FATHER_AFTER);
                            }
                            else {
                                seq_lines = TALK_FATHER;
                                seq_len = TALK_LEN(TALK_FATHER);
                            }
                            break;
                        case 'S':
                            if(!got_shelf) {
                                got_shelf = 1;
                                seq_lines = TALK_SHELF;
                                seq_len = TALK_LEN(TALK_SHELF);
                            }
                            else {
                                seq_lines = TALK_SHELF_EMPTY;
                                seq_len = TALK_LEN(TALK_SHELF_EMPTY);
                            }
                            break;
                        case 'C':
                            if(!looted_crate) {
                                looted_crate = 1;
                                bag.bandage++;
                                seq_lines = TALK_CRATE;
                                seq_len = TALK_LEN(TALK_CRATE);
                            }
                            else {
                                seq_lines = TALK_CRATE_EMPTY;
                                seq_len = TALK_LEN(TALK_CRATE_EMPTY);
                            }
                            break;
                        default:
                            break;
                    }
                    seq_beat = 0;
                }
            }

            /* Menu open, only from plain world state (state.lua only
               reaches selectPressed()/startPressed() outside TALK/
               BATTLE/etc, which here just means no dialogue active). */
            if(!seq_lines) {
                if(y_now && !prev_y)
                    menu_mode = 1;
                else if(start_now && !prev_start)
                    menu_mode = 2;
            }
        }

        /* Draw every frame, unconditionally, into the buffer that was
           just hidden by the flip above. See the fb_flip comment for
           why this has to be unconditional now, unlike the earlier
           dirty-check versions. */
        if(state == 0) {
            draw_press_start();
        }
        else {
            draw_house_background();
            draw_props();
            draw_player(px, py, pdir);
            draw_hud(got_shelf, looted_crate, bag.bandage);
            if(seq_lines)
                draw_dialogue_box(seq_lines[seq_beat]);
            if(menu_mode == 1)
                draw_bag_menu(&bag);
            else if(menu_mode == 2)
                draw_party_menu(got_shelf);
        }

        prev_start = start_now;
        prev_b = b_now;
        prev_y = y_now;
        prev_a = a_now;
    }
}
