/* Auto-generated by scripts/gen_sprites.py -- do not edit by hand. */
#ifndef BEELZ_SPRITE_DATA_H
#define BEELZ_SPRITE_DATA_H

typedef struct { int start; int count; int fps; int loop; } bz_anim_t;
typedef struct {
    const char *pvr_file;
    int frame_w, frame_h, sheet_w, sheet_h, cols;
} bz_sheet_t;
typedef struct { const char *pvr_file; int w, h, tile_x; } bz_bg_t;

static const bz_sheet_t SHEET_PLAYER = {
    "/cd/textures/player.pvr", 64, 64, 512, 512, 8
};
static const bz_anim_t PLAYER_ANIM_IDLE = {0, 4, 5, 1};
static const bz_anim_t PLAYER_ANIM_RUN = {4, 4, 10, 1};
static const bz_anim_t PLAYER_ANIM_ATTACK1 = {8, 4, 14, 0};
static const bz_anim_t PLAYER_ANIM_ATTACK2 = {12, 4, 14, 0};
static const bz_anim_t PLAYER_ANIM_ATTACK3 = {16, 4, 16, 0};
static const bz_anim_t PLAYER_ANIM_ATTACK4 = {20, 5, 14, 0};
static const bz_anim_t PLAYER_ANIM_PARRY = {25, 2, 12, 0};
static const bz_anim_t PLAYER_ANIM_BLOCK = {27, 2, 6, 1};
static const bz_anim_t PLAYER_ANIM_HIT = {29, 2, 8, 0};
static const bz_anim_t PLAYER_ANIM_DEATH = {31, 5, 6, 0};

static const bz_sheet_t SHEET_IMP = {
    "/cd/textures/imp.pvr", 64, 64, 256, 256, 4
};
static const bz_anim_t IMP_ANIM_IDLE = {0, 3, 4, 1};
static const bz_anim_t IMP_ANIM_WALK = {3, 4, 9, 1};
static const bz_anim_t IMP_ANIM_ATTACK = {7, 3, 12, 0};
static const bz_anim_t IMP_ANIM_DEATH = {10, 3, 6, 0};

static const bz_sheet_t SHEET_THRALL = {
    "/cd/textures/thrall.pvr", 64, 64, 256, 256, 4
};
static const bz_anim_t THRALL_ANIM_IDLE = {0, 2, 3, 1};
static const bz_anim_t THRALL_ANIM_WALK = {2, 4, 8, 1};
static const bz_anim_t THRALL_ANIM_ATTACK = {6, 3, 11, 0};
static const bz_anim_t THRALL_ANIM_DEATH = {9, 3, 6, 0};

static const bz_sheet_t SHEET_BOSS = {
    "/cd/textures/boss.pvr", 128, 128, 1024, 512, 8
};
static const bz_anim_t BOSS_ANIM_IDLE = {0, 4, 4, 1};
static const bz_anim_t BOSS_ANIM_WALK = {4, 4, 6, 1};
static const bz_anim_t BOSS_ANIM_ATTACK_SWEEP = {8, 4, 10, 0};
static const bz_anim_t BOSS_ANIM_ATTACK_SLAM = {12, 4, 8, 0};
static const bz_anim_t BOSS_ANIM_ATTACK_CAST = {16, 4, 8, 0};
static const bz_anim_t BOSS_ANIM_HURT = {20, 2, 8, 0};
static const bz_anim_t BOSS_ANIM_DEATH = {22, 6, 5, 0};

static const bz_sheet_t SHEET_FIREBALL = {
    "/cd/textures/fireball.pvr", 64, 64, 128, 128, 2
};
static const bz_anim_t FIREBALL_ANIM_SPIN = {0, 4, 12, 1};

static const bz_sheet_t SHEET_UI_ICONS = {
    "/cd/textures/ui_icons.pvr", 32, 32, 128, 64, 4
};
#define UI_ICON_A 0
#define UI_ICON_B 1
#define UI_ICON_X 2
#define UI_ICON_Y 3
#define UI_ICON_L 4
#define UI_ICON_R 5

static const bz_sheet_t SHEET_BAR_HEALTH = {
    "/cd/textures/bar_health.pvr", 256, 16, 256, 16, 1
};

static const bz_sheet_t SHEET_BAR_STAMINA = {
    "/cd/textures/bar_stamina.pvr", 256, 16, 256, 16, 1
};

static const bz_sheet_t SHEET_BAR_BOSS = {
    "/cd/textures/bar_boss.pvr", 512, 16, 512, 16, 1
};

/* backgrounds */
static const bz_bg_t BG_SKY = {"/cd/textures/sky.pvr", 512, 256, 0};
static const bz_bg_t BG_SKY_BOSS = {"/cd/textures/sky_boss.pvr", 512, 256, 0};
static const bz_bg_t BG_LAYER_FAR = {"/cd/textures/layer_far.pvr", 1024, 256, 1};
static const bz_bg_t BG_LAYER_MID = {"/cd/textures/layer_mid.pvr", 1024, 256, 1};
static const bz_bg_t BG_GROUND = {"/cd/textures/ground.pvr", 128, 64, 1};
static const bz_bg_t BG_GATE = {"/cd/textures/gate.pvr", 128, 256, 0};

#endif /* BEELZ_SPRITE_DATA_H */
