/* Auto-generated by scripts/gen_sprites.py -- do not edit. */
#ifndef BEELZ_SPRITE_DATA_H
#define BEELZ_SPRITE_DATA_H

typedef struct { int start; int count; int fps; int loop; } bz_anim_t;
typedef struct {
    const char *pvr_file;
    int frame_w, frame_h, sheet_w, sheet_h, cols;
    float anchor_x, anchor_y;   /* where the actor's feet/centre sit */
    float draw_w, draw_h;       /* on-screen quad size at 480p    */
} bz_sheet_t;
typedef struct { const char *pvr_file; int w, h, tile_x; } bz_bg_t;

static const bz_sheet_t SHEET_PLAYER = {
    "/cd/textures/player.pvr", 112, 112, 512, 1024, 4, 42.0f, 102.0f, 166.8f, 166.8f
};
static const bz_anim_t PLAYER_ANIM_IDLE = {0, 4, 5, 1};
static const bz_anim_t PLAYER_ANIM_RUN = {4, 4, 11, 1};
static const bz_anim_t PLAYER_ANIM_ATTACK1 = {8, 4, 14, 0};
static const bz_anim_t PLAYER_ANIM_ATTACK2 = {12, 4, 14, 0};
static const bz_anim_t PLAYER_ANIM_ATTACK3 = {16, 4, 16, 0};
static const bz_anim_t PLAYER_ANIM_ATTACK4 = {20, 5, 14, 0};
static const bz_anim_t PLAYER_ANIM_PARRY = {25, 2, 12, 0};
static const bz_anim_t PLAYER_ANIM_BLOCK = {27, 2, 6, 1};
static const bz_anim_t PLAYER_ANIM_HIT = {29, 2, 9, 0};
static const bz_anim_t PLAYER_ANIM_DEATH = {31, 5, 6, 0};

static const bz_sheet_t SHEET_IMP = {
    "/cd/textures/imp.pvr", 96, 96, 256, 1024, 2, 48.0f, 86.0f, 82.6f, 82.6f
};
static const bz_anim_t IMP_ANIM_IDLE = {0, 3, 5, 1};
static const bz_anim_t IMP_ANIM_WALK = {3, 4, 10, 1};
static const bz_anim_t IMP_ANIM_ATTACK = {7, 3, 12, 0};
static const bz_anim_t IMP_ANIM_DEATH = {10, 3, 7, 0};

static const bz_sheet_t SHEET_THRALL = {
    "/cd/textures/thrall.pvr", 96, 96, 256, 1024, 2, 48.0f, 88.0f, 98.1f, 98.1f
};
static const bz_anim_t THRALL_ANIM_IDLE = {0, 2, 3, 1};
static const bz_anim_t THRALL_ANIM_WALK = {2, 4, 9, 1};
static const bz_anim_t THRALL_ANIM_ATTACK = {6, 3, 11, 0};
static const bz_anim_t THRALL_ANIM_DEATH = {9, 3, 7, 0};

static const bz_sheet_t SHEET_BOSS = {
    "/cd/textures/boss.pvr", 144, 144, 512, 1024, 3, 72.0f, 134.0f, 266.2f, 266.2f
};
static const bz_anim_t BOSS_ANIM_IDLE = {0, 3, 5, 1};
static const bz_anim_t BOSS_ANIM_WALK = {3, 3, 7, 1};
static const bz_anim_t BOSS_ANIM_ATTACK_SWEEP = {6, 3, 10, 0};
static const bz_anim_t BOSS_ANIM_ATTACK_SLAM = {9, 3, 9, 0};
static const bz_anim_t BOSS_ANIM_ATTACK_CAST = {12, 2, 8, 0};
static const bz_anim_t BOSS_ANIM_HURT = {14, 2, 9, 0};
static const bz_anim_t BOSS_ANIM_DEATH = {16, 4, 5, 0};

static const bz_sheet_t SHEET_FIREBALL = {
    "/cd/textures/fireball.pvr", 48, 48, 64, 512, 1, 24.0f, 24.0f, 47.6f, 47.6f
};
static const bz_anim_t FIREBALL_ANIM_SPIN = {0, 6, 14, 1};

static const bz_sheet_t SHEET_SHADOW = {
    "/cd/textures/shadow.pvr", 64, 32, 64, 32, 1, 32.0f, 16.0f, 64.0f, 32.0f
};

static const bz_sheet_t SHEET_UI_ICONS = {
    "/cd/textures/ui_icons.pvr", 40, 40, 64, 256, 1, 20.0f, 20.0f, 40.0f, 40.0f
};
#define UI_ICON_A 0
#define UI_ICON_B 1
#define UI_ICON_X 2
#define UI_ICON_Y 3
#define UI_ICON_L 4
#define UI_ICON_R 5

/* backgrounds */
static const bz_bg_t BG_SKY = {"/cd/textures/sky.pvr", 64, 256, 0};
static const bz_bg_t BG_SKY_BOSS = {"/cd/textures/sky_boss.pvr", 64, 256, 0};
static const bz_bg_t BG_LAYER_FAR = {"/cd/textures/layer_far.pvr", 1024, 256, 1};
static const bz_bg_t BG_LAYER_MID = {"/cd/textures/layer_mid.pvr", 1024, 256, 1};
static const bz_bg_t BG_GROUND = {"/cd/textures/ground.pvr", 256, 128, 1};
static const bz_bg_t BG_GATE = {"/cd/textures/gate.pvr", 128, 256, 0};

#endif /* BEELZ_SPRITE_DATA_H */
